
create table if not exists public.reports (
  "id" text primary key,
  "cityKey" text,
  "title" text not null,
  "ward" text,
  "status" text not null,
  "severity" text,
  "confidence" integer,
  "contractor" text,
  "txHash" text,
  "warrantyDaysLeft" integer,
  "location" text,
  "latitude" double precision,
  "longitude" double precision,
  "mapUrl" text,
  "issueCategory" text,
  "assetType" text,
  "aiSummary" text,
  "recommendedAction" text,
  "slaHours" integer,
  "createdAt" timestamptz default now(),
  "updatedAt" timestamptz default now(),
  "issueImageName" text,
  "repairImageName" text,
  "repairProofAt" timestamptz,
  "warrantyActivatedAt" timestamptz,
  "warrantyExpiresAt" timestamptz,
  "warrantyPeriodDays" integer,
  "evidenceHash" text,
  "proofBundleHash" text,
  "repairEvidenceHash" text,
  "repairTxHash" text,
  "aiPriorityScore" integer,
  "imageEvidenceScore" integer,
  "aiModelVersion" text,
  "estimatedImpact" text,
  "ownerVerified" boolean default false,
  "closedAt" timestamptz,
  "closureNote" text,
  "publicFeedback" jsonb default '[]'::jsonb,
  "utilityRestoration" jsonb,
  "repairAudit" jsonb,
  "history" jsonb default '[]'::jsonb
);

create index if not exists reports_city_key_idx on public.reports ("cityKey");
create index if not exists reports_status_idx on public.reports ("status");
create index if not exists reports_created_at_idx on public.reports ("createdAt" desc);
