export type LanguageKey =
  | "en"
  | "hi"
  | "mr"
  | "bn"
  | "ta"
  | "te"
  | "gu"
  | "kn";

export type LanguageOption = {
  key: LanguageKey;
  label: string;
  nativeLabel: string;
};

export const DEFAULT_LANGUAGE_KEY: LanguageKey = "en";

export const indianLanguages: LanguageOption[] = [
  { key: "en", label: "English", nativeLabel: "English" },
  { key: "hi", label: "Hindi", nativeLabel: "हिन्दी" },
  { key: "mr", label: "Marathi", nativeLabel: "मराठी" },
  { key: "bn", label: "Bengali", nativeLabel: "বাংলা" },
  { key: "ta", label: "Tamil", nativeLabel: "தமிழ்" },
  { key: "te", label: "Telugu", nativeLabel: "తెలుగు" },
  { key: "gu", label: "Gujarati", nativeLabel: "ગુજરાતી" },
  { key: "kn", label: "Kannada", nativeLabel: "ಕನ್ನಡ" },
];

const en = {
  about: "About",
  accountabilityImpact: "Accountability Impact",
  active: "Active",
  activeReports: "Active Reports",
  afterRepairProofAttached: "After-repair proof attached",
  aiClassifierOnline: "AI classifier online",
  aiConfidence: "AI Confidence",
  aiDiagnosticsVerdict: "AI Diagnostics Verdict",
  aiIssueBrain: "AI Issue Brain",
  aiPreVerification: "AI Pre-Verification",
  aiRepairAudit: "AI Repair Audit",
  aiVerdict: "AI Verdict",
  analyzeIssue: "Analyze Infrastructure Issue",
  asset: "Asset",
  awaitingContractorAssignment: "Awaiting contractor assignment",
  backToCommandCenter: "Back to Command Center",
  blockchainProof: "Fabric-ready Proof",
  blockchainTransaction: "Proof transaction reference",
  chainStatus: "Ledger Status",
  city: "City",
  cityCoverage: "Demo City Coverage",
  citizenIdentity: "Citizen Identity",
  citizenIssueBefore: "Citizen Issue Before",
  citizenNode: "Citizen Node",
  citizenReport: "Citizen Report",
  citizenWallet: "Citizen Wallet",
  commandCenter: "Command Center",
  commandCenterSubtitle: "Command Center | Multi-city Proof Network",
  connectWallet: "Connect Wallet",
  contractor: "Contractor",
  contractorAudit: "Contractor Audit",
  contractorProofAfter: "Contractor Proof After",
  contractorRepairAudit: "Contractor Repair Audit",
  contractorRepairProofLinked: "Contractor repair proof linked to report ID",
  contractorView: "Contractor View",
  createProof: "Create AI/RAG Proof",
  demoMode: "Demo mode",
  documentation: "Documentation",
  duplicateRisk: "Duplicate Risk",
  evidenceComparison: "Evidence Comparison",
  exactPublicLocation: "Exact public location",
  failureTracked: "Failure tracked",
  filingNode: "Filing node",
  geoMatch: "Geo Match",
  governance: "Governance",
  hashAnchored: "Hash anchored",
  highPriority: "High Priority",
  issueBefore: "Citizen Issue Before",
  issueImageVisible: "Issue image visible",
  language: "Language",
  latestCitizenReport: "Latest Citizen Report",
  liveCivicStream: "Live civic stream",
  mapLocation: "Google Map Location",
  mapLocationSubtitle: "Use GPS or enter coordinates to pin the exact civic issue location.",
  manualCoordinates: "Manual Coordinates",
  newProof: "New Proof",
  newProofCreated: "New Proof Created",
  noRepairProofYet: "No repair proof submitted yet",
  nodeSynced: "Node synced",
  notActive: "Not Active",
  notJustReporting: "Not Just Reporting",
  notJustReportingText: "AI/RAG proof records keep repair evidence, contractor accountability, and warranty history visible.",
  onChainProofs: "Fabric-ready Proofs",
  oneReportFlow: "One report flow",
  openGoogleMaps: "Open Google Maps",
  openIssues: "Open Issues",
  openPublicProof: "Open Public Proof",
  openWarrantyRegistry: "Open Warranty Registry",
  pending: "Pending",
  pendingProof: "Pending Proof",
  proofEventsIndexed: "Proof events indexed",
  proofTimeline: "Proof Timeline",
  publicAudit: "Public Audit",
  publicCase: "Public case",
  publicEvidenceState: "Public Evidence State",
  publicHash: "Public Hash",
  publicIssueHistory: "Public Issue History",
  publicLedgerReady: "Public ledger ready",
  publicProof: "Public Proof",
  publicProofTimeline: "Public Proof Timeline",
  publicRegistry: "Public Warranty Registry",
  publicRegistrySubtitle: "Citizens can see every reported issue, pending repair, contractor proof and active warranty.",
  publicStatus: "Public Status",
  publicStatusUpdates: "Public status updates in sync",
  quickIssueTypes: "Quick Demo Issue Types",
  ready: "Ready",
  readyToSign: "Ready to sign civic proof records",
  repairImageVisible: "Repair image visible",
  repairIntegrity: "Repair Integrity",
  repairProof: "Repair Proof",
  repairSubmitted: "Repair Submitted",
  repeatFailure: "Repeat Failure",
  repeatFailureDetected: "Repeat Failure Detected",
  repeatFailureScan: "Repeat failure scan",
  reportIssue: "Report Issue",
  reportIssuePlaceholder: "Describe any civic infrastructure issue: road, drain, streetlight, garbage, water leakage, footpath...",
  resetDemo: "Reset Demo",
  resolverReputationActive: "Resolver reputation active",
  runAiRepairAudit: "Run AI Repair Audit",
  scanRepeatFailure: "Scan Repeat Failure",
  selectedAddress: "Selected Address",
  selectedCase: "Selected public case",
  severity: "Severity",
  signAndCreate: "Sign and Create",
  status: "Status",
  submitProofActivateWarranty: "Submit Proof & Activate Warranty",
  submitReport: "Submit Report",
  syncedWarrantyRegistry: "Synced warranty registry",
  systemStatus: "System Status",
  technicalObservation: "Technical Observation",
  underWarranty: "Under Warranty",
  unifiedAnalysis: "Unified issue analysis",
  universalInfrastructureEvidence: "Universal Infrastructure Evidence",
  uploadAfterRepairEvidence: "Upload After-Repair Evidence",
  uploadAfterRepairHint: "This image will be public on proof view",
  uploadCivicEvidence: "Drag and drop civic issue evidence",
  uploadClickBrowse: "or click to browse local device",
  urbanLedger: "Urban Ledger",
  useCurrentGps: "Use Current GPS",
  verifiedRepairs: "Verified Repairs",
  viewContract: "View Contract",
  viewOnCommandCenter: "View On Command Center",
  walletReady: "Wallet ready",
  ward: "Ward",
  warranty: "Warranty",
  warrantyActivated: "Warranty activated",
  warrantyGuard: "Warranty Guard",
  warrantyOracleListening: "Warranty oracle listening",
  warrantyScanner: "Warranty Scanner",
  warrantyStateVisible: "Warranty state visible to citizens",
  warrantyWatch: "Warranty Watch",
  // Auth page
  signUp: "Sign up",
  login: "Login",
  dashboard: "Dashboard",
  roleBasedAccess: "Role based access",
  verifyPersonBeforeProof: "Verify the person before the proof.",
  authPageSubtitle: "Citizens, contractors, and ward admins get different dashboards. Every profile receives a proof hash that can later be written to your CityPramaan smart contract.",
  enterEmailOtp: "Enter email OTP",
  createCityPraamanProfile: "Create CityPramaan profile",
  welcomeBack: "Welcome back",
  codeSentTo: "Code sent to",
  signingUpAs: "Signing up as",
  loginWithEmail: "Login with your registered email and password.",
  fullName: "Full name",
  contactNumber: "Contact number",
  contractorIdentityArea: "Contractor identity and service area",
  contractorIdNo: "Contractor ID / identity no.",
  companyAgency: "Company / agency",
  assignedAreaLocality: "Assigned area / locality",
  assignedWardZone: "Assigned ward / zone",
  workCategorySpecialization: "Work category / specialization",
  verificationEmail: "Verification email",
  otpCode: "OTP code",
  resendCode: "Resend code",
  emailAddress: "Email address",
  password: "Password",
  processing: "Processing...",
  verifyEmail: "Verify email",
  createAccount: "Create account",
  verificationEmailSent: "Verification email sent.",
  verificationEmailSentAgain: "Verification email sent again.",
  authFailed: "Authentication failed.",
  couldNotResend: "Could not resend verification code.",
  roleUserDetail: "Report civic issues and track public proof.",
  roleAdminDetail: "Review ward reports, approvals, and warranty cases.",
  roleContractorDetail: "Register identity, area, category, and submit repair proof.",
  roadRepair: "Road repair",
  drainage: "Drainage",
  streetlight: "Streetlight",
  garbageCleanup: "Garbage cleanup",
  waterLeakage: "Water leakage",
  footpathRepair: "Footpath repair",
  powerOutage: "Power outage",
  generalCivicRepair: "General civic repair",
} as const;

export type TranslationKey = keyof typeof en;

const translations: Record<LanguageKey, Record<TranslationKey, string>> = {
  en,
  hi: {
    about: "परिचय",
    accountabilityImpact: "जवाबदेही प्रभाव",
    active: "सक्रिय",
    activeReports: "सक्रिय रिपोर्ट",
    afterRepairProofAttached: "मरम्मत के बाद प्रमाण जुड़ा",
    aiClassifierOnline: "AI वर्गीकरण चालू",
    aiConfidence: "AI विश्वास",
    aiDiagnosticsVerdict: "AI निदान परिणाम",
    aiIssueBrain: "AI समस्या इंजन",
    aiPreVerification: "AI पूर्व सत्यापन",
    aiRepairAudit: "AI मरम्मत ऑडिट",
    aiVerdict: "AI निर्णय",
    analyzeIssue: "इंफ्रास्ट्रक्चर समस्या विश्लेषण",
    asset: "संपत्ति",
    awaitingContractorAssignment: "ठेकेदार असाइनमेंट प्रतीक्षारत",
    backToCommandCenter: "कमांड सेंटर पर वापस",
    blockchainProof: "ब्लॉकचेन प्रमाण",
    blockchainTransaction: "ब्लॉकचेन लेनदेन",
    chainStatus: "चेन स्थिति",
    city: "शहर",
    cityCoverage: "डेमो शहर कवरेज",
    citizenIdentity: "नागरिक पहचान",
    citizenIssueBefore: "नागरिक समस्या फोटो",
    citizenNode: "नागरिक नोड",
    citizenReport: "नागरिक रिपोर्ट",
    citizenWallet: "नागरिक वॉलेट",
    commandCenter: "कमांड सेंटर",
    commandCenterSubtitle: "कमांड सेंटर | बहु-शहर प्रमाण नेटवर्क",
    connectWallet: "वॉलेट जोड़ें",
    contractor: "ठेकेदार",
    contractorAudit: "ठेकेदार ऑडिट",
    contractorProofAfter: "मरम्मत के बाद ठेकेदार प्रमाण",
    contractorRepairAudit: "ठेकेदार मरम्मत ऑडिट",
    contractorRepairProofLinked: "ठेकेदार मरम्मत प्रमाण रिपोर्ट ID से जुड़ा",
    contractorView: "ठेकेदार दृश्य",
    createProof: "ब्लॉकचेन प्रमाण बनाएं",
    demoMode: "डेमो मोड",
    documentation: "दस्तावेज",
    duplicateRisk: "डुप्लिकेट जोखिम",
    evidenceComparison: "प्रमाण तुलना",
    exactPublicLocation: "सटीक सार्वजनिक स्थान",
    failureTracked: "विफलता ट्रैक की गई",
    filingNode: "फाइलिंग नोड",
    geoMatch: "स्थान मिलान",
    governance: "शासन",
    hashAnchored: "हैश एंकर",
    highPriority: "उच्च प्राथमिकता",
    issueBefore: "नागरिक समस्या फोटो",
    issueImageVisible: "समस्या फोटो दिखाई दे रहा है",
    language: "भाषा",
    latestCitizenReport: "नवीनतम नागरिक रिपोर्ट",
    liveCivicStream: "लाइव नागरिक स्ट्रीम",
    mapLocation: "गूगल मैप स्थान",
    mapLocationSubtitle: "सटीक स्थान पिन करने के लिए GPS या निर्देशांक दर्ज करें।",
    manualCoordinates: "मैनुअल निर्देशांक",
    newProof: "नया प्रमाण",
    newProofCreated: "नया प्रमाण बना",
    noRepairProofYet: "अभी मरम्मत प्रमाण नहीं दिया गया",
    nodeSynced: "नोड सिंक",
    notActive: "सक्रिय नहीं",
    notJustReporting: "सिर्फ रिपोर्टिंग नहीं",
    notJustReportingText: "ब्लॉकचेन-समर्थित वारंटी सत्यापन ठेकेदारों को सार्वजनिक प्रमाण के साथ दोबारा आई समस्याएं ठीक कराने में मदद करता है।",
    onChainProofs: "ऑन-चेन प्रमाण",
    oneReportFlow: "एक रिपोर्ट प्रवाह",
    openGoogleMaps: "गूगल मैप खोलें",
    openIssues: "खुली समस्याएं",
    openPublicProof: "सार्वजनिक प्रमाण खोलें",
    openWarrantyRegistry: "वारंटी रजिस्ट्री खोलें",
    pending: "लंबित",
    pendingProof: "प्रमाण लंबित",
    proofEventsIndexed: "प्रमाण घटनाएं इंडेक्स",
    proofTimeline: "प्रमाण टाइमलाइन",
    publicAudit: "सार्वजनिक ऑडिट",
    publicCase: "सार्वजनिक केस",
    publicEvidenceState: "सार्वजनिक प्रमाण स्थिति",
    publicHash: "सार्वजनिक हैश",
    publicIssueHistory: "सार्वजनिक समस्या इतिहास",
    publicLedgerReady: "सार्वजनिक लेजर तैयार",
    publicProof: "सार्वजनिक प्रमाण",
    publicProofTimeline: "सार्वजनिक प्रमाण टाइमलाइन",
    publicRegistry: "सार्वजनिक वारंटी रजिस्ट्री",
    publicRegistrySubtitle: "नागरिक हर रिपोर्ट, लंबित मरम्मत, ठेकेदार प्रमाण और सक्रिय वारंटी देख सकते हैं।",
    publicStatus: "सार्वजनिक स्थिति",
    publicStatusUpdates: "सार्वजनिक स्थिति सिंक है",
    quickIssueTypes: "त्वरित डेमो समस्या प्रकार",
    ready: "तैयार",
    readyToSign: "नागरिक प्रमाण रिकॉर्ड साइन करने के लिए तैयार",
    repairImageVisible: "मरम्मत फोटो दिखाई दे रहा है",
    repairIntegrity: "मरम्मत गुणवत्ता",
    repairProof: "मरम्मत प्रमाण",
    repairSubmitted: "मरम्मत जमा",
    repeatFailure: "दोहराई विफलता",
    repeatFailureDetected: "दोहराई विफलता मिली",
    repeatFailureScan: "दोहराई विफलता स्कैन",
    reportIssue: "समस्या रिपोर्ट करें",
    reportIssuePlaceholder: "किसी भी नागरिक इंफ्रास्ट्रक्चर समस्या का वर्णन करें: सड़क, नाली, स्ट्रीटलाइट, कचरा, पानी रिसाव, फुटपाथ...",
    resetDemo: "डेमो रीसेट",
    resolverReputationActive: "रिजॉल्वर प्रतिष्ठा सक्रिय",
    runAiRepairAudit: "AI मरम्मत ऑडिट चलाएं",
    scanRepeatFailure: "दोहराई विफलता स्कैन करें",
    selectedAddress: "चयनित पता",
    selectedCase: "चयनित सार्वजनिक केस",
    severity: "गंभीरता",
    signAndCreate: "साइन करके बनाएं",
    status: "स्थिति",
    submitProofActivateWarranty: "प्रमाण जमा करें और वारंटी सक्रिय करें",
    submitReport: "रिपोर्ट जमा करें",
    syncedWarrantyRegistry: "सिंक वारंटी रजिस्ट्री",
    systemStatus: "सिस्टम स्थिति",
    technicalObservation: "तकनीकी अवलोकन",
    underWarranty: "वारंटी में",
    unifiedAnalysis: "एकीकृत समस्या विश्लेषण",
    universalInfrastructureEvidence: "सार्वभौमिक इंफ्रास्ट्रक्चर प्रमाण",
    uploadAfterRepairEvidence: "मरम्मत के बाद फोटो अपलोड करें",
    uploadAfterRepairHint: "यह फोटो सार्वजनिक प्रमाण पेज पर दिखेगा",
    uploadCivicEvidence: "नागरिक समस्या प्रमाण खींचकर छोड़ें",
    uploadClickBrowse: "या डिवाइस से चुनने के लिए क्लिक करें",
    urbanLedger: "शहरी लेजर",
    useCurrentGps: "मेरा GPS उपयोग करें",
    verifiedRepairs: "सत्यापित मरम्मत",
    viewContract: "कॉन्ट्रैक्ट देखें",
    viewOnCommandCenter: "कमांड सेंटर में देखें",
    walletReady: "वॉलेट तैयार",
    ward: "वार्ड",
    warranty: "वारंटी",
    warrantyActivated: "वारंटी सक्रिय",
    warrantyGuard: "वारंटी गार्ड",
    warrantyOracleListening: "वारंटी ऑरेकल सुन रहा है",
    warrantyScanner: "वारंटी स्कैनर",
    warrantyStateVisible: "वारंटी स्थिति नागरिकों को दिखाई देती है",
    warrantyWatch: "वारंटी निगरानी",
    signUp: "साइन अप",
    login: "लॉगिन",
    dashboard: "डैशबोर्ड",
    roleBasedAccess: "भूमिका आधारित पहुंच",
    verifyPersonBeforeProof: "प्रमाण से पहले व्यक्ति को सत्यापित करें।",
    authPageSubtitle: "नागरिक, ठेकेदार और वार्ड एडमिन को अलग-अलग डैशबोर्ड मिलते हैं। हर प्रोफाइल को एक प्रूफ हैश मिलता है।",
    enterEmailOtp: "ईमेल OTP दर्ज करें",
    createCityPraamanProfile: "CityPramaan प्रोफाइल बनाएं",
    welcomeBack: "वापस आपका स्वागत है",
    codeSentTo: "कोड भेजा गया",
    signingUpAs: "साइन अप हो रहे हैं",
    loginWithEmail: "अपने पंजीकृत ईमेल और पासवर्ड से लॉगिन करें।",
    fullName: "पूरा नाम",
    contactNumber: "संपर्क नंबर",
    contractorIdentityArea: "ठेकेदार पहचान और सेवा क्षेत्र",
    contractorIdNo: "ठेकेदार ID / पहचान नंबर",
    companyAgency: "कंपनी / एजेंसी",
    assignedAreaLocality: "असाइन क्षेत्र / इलाका",
    assignedWardZone: "असाइन वार्ड / ज़ोन",
    workCategorySpecialization: "कार्य श्रेणी / विशेषता",
    verificationEmail: "सत्यापन ईमेल",
    otpCode: "OTP कोड",
    resendCode: "कोड फिर भेजें",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    processing: "प्रोसेस हो रहा है...",
    verifyEmail: "ईमेल सत्यापित करें",
    createAccount: "खाता बनाएं",
    verificationEmailSent: "सत्यापन ईमेल भेजा गया।",
    verificationEmailSentAgain: "सत्यापन ईमेल फिर भेजा गया।",
    authFailed: "प्रमाणीकरण विफल।",
    couldNotResend: "सत्यापन कोड फिर नहीं भेज सका।",
    roleUserDetail: "नागरिक समस्याएं रिपोर्ट करें और सार्वजनिक प्रमाण ट्रैक करें।",
    roleAdminDetail: "वार्ड रिपोर्ट, अनुमोदन और वारंटी केस की समीक्षा करें।",
    roleContractorDetail: "पहचान, क्षेत्र, श्रेणी पंजीकृत करें और मरम्मत प्रमाण जमा करें।",
    roadRepair: "सड़क मरम्मत",
    drainage: "नाली",
    streetlight: "स्ट्रीटलाइट",
    garbageCleanup: "कचरा सफाई",
    waterLeakage: "पानी रिसाव",
    footpathRepair: "फुटपाथ मरम्मत",
    powerOutage: "बिजली कटौती",
    generalCivicRepair: "सामान्य नागरिक मरम्मत",
  },
  mr: {
    about: "परिचय",
    accountabilityImpact: "जबाबदारी परिणाम",
    active: "सक्रिय",
    activeReports: "सक्रिय अहवाल",
    afterRepairProofAttached: "दुरुस्तीनंतरचा पुरावा जोडला",
    aiClassifierOnline: "AI वर्गीकरण सुरू",
    aiConfidence: "AI विश्वास",
    aiDiagnosticsVerdict: "AI निदान निकाल",
    aiIssueBrain: "AI समस्या इंजिन",
    aiPreVerification: "AI पूर्व-सत्यापन",
    aiRepairAudit: "AI दुरुस्ती ऑडिट",
    aiVerdict: "AI निकाल",
    analyzeIssue: "समस्या विश्लेषण करा",
    asset: "मालमत्ता",
    awaitingContractorAssignment: "कंत्राटदार नेमणूक प्रतीक्षेत",
    backToCommandCenter: "कमांड सेंटरवर परत",
    blockchainProof: "ब्लॉकचेन पुरावा",
    blockchainTransaction: "ब्लॉकचेन व्यवहार",
    chainStatus: "चेन स्थिती",
    city: "शहर",
    cityCoverage: "डेमो शहर कव्हरेज",
    citizenIdentity: "नागरिक ओळख",
    citizenIssueBefore: "नागरिक समस्या फोटो",
    citizenNode: "नागरिक नोड",
    citizenReport: "नागरिक अहवाल",
    citizenWallet: "नागरिक वॉलेट",
    commandCenter: "कमांड सेंटर",
    commandCenterSubtitle: "कमांड सेंटर | बहु-शहर पुरावा नेटवर्क",
    connectWallet: "वॉलेट जोडा",
    contractor: "कंत्राटदार",
    contractorAudit: "कंत्राटदार ऑडिट",
    contractorProofAfter: "दुरुस्तीनंतर कंत्राटदार पुरावा",
    contractorRepairAudit: "कंत्राटदार दुरुस्ती ऑडिट",
    contractorRepairProofLinked: "कंत्राटदार पुरावा अहवाल ID शी जोडला",
    contractorView: "कंत्राटदार दृश्य",
    createProof: "ब्लॉकचेन पुरावा तयार करा",
    demoMode: "डेमो मोड",
    documentation: "दस्तऐवज",
    duplicateRisk: "डुप्लिकेट धोका",
    evidenceComparison: "पुरावा तुलना",
    exactPublicLocation: "अचूक सार्वजनिक स्थान",
    failureTracked: "बिघाड ट्रॅक झाला",
    filingNode: "फाइलिंग नोड",
    geoMatch: "स्थान जुळणी",
    governance: "शासन",
    hashAnchored: "हॅश अँकर",
    highPriority: "उच्च प्राधान्य",
    issueBefore: "नागरिक समस्या फोटो",
    issueImageVisible: "समस्या फोटो दिसत आहे",
    language: "भाषा",
    latestCitizenReport: "नवीनतम नागरिक अहवाल",
    liveCivicStream: "लाईव्ह नागरी प्रवाह",
    mapLocation: "गूगल मॅप स्थान",
    mapLocationSubtitle: "अचूक स्थानासाठी GPS किंवा निर्देशांक वापरा.",
    manualCoordinates: "मॅन्युअल निर्देशांक",
    newProof: "नवीन पुरावा",
    newProofCreated: "नवीन पुरावा तयार",
    noRepairProofYet: "अजून दुरुस्ती पुरावा नाही",
    nodeSynced: "नोड सिंक",
    notActive: "सक्रिय नाही",
    notJustReporting: "फक्त रिपोर्टिंग नाही",
    notJustReportingText: "ब्लॉकचेन-समर्थित वारंटी सत्यापन सार्वजनिक पुराव्यासह पुन्हा आलेल्या समस्या दुरुस्त करायला मदत करते.",
    onChainProofs: "ऑन-चेन पुरावे",
    oneReportFlow: "एक अहवाल प्रवाह",
    openGoogleMaps: "गूगल मॅप उघडा",
    openIssues: "खुल्या समस्या",
    openPublicProof: "सार्वजनिक पुरावा उघडा",
    openWarrantyRegistry: "वारंटी नोंदणी उघडा",
    pending: "प्रलंबित",
    pendingProof: "पुरावा प्रलंबित",
    proofEventsIndexed: "पुरावा घटना इंडेक्स",
    proofTimeline: "पुरावा टाइमलाइन",
    publicAudit: "सार्वजनिक ऑडिट",
    publicCase: "सार्वजनिक केस",
    publicEvidenceState: "सार्वजनिक पुरावा स्थिती",
    publicHash: "सार्वजनिक हॅश",
    publicIssueHistory: "सार्वजनिक समस्या इतिहास",
    publicLedgerReady: "सार्वजनिक लेजर तयार",
    publicProof: "सार्वजनिक पुरावा",
    publicProofTimeline: "सार्वजनिक पुरावा टाइमलाइन",
    publicRegistry: "सार्वजनिक वारंटी नोंदणी",
    publicRegistrySubtitle: "नागरिक रिपोर्ट, प्रलंबित दुरुस्ती, कंत्राटदार पुरावा आणि सक्रिय वारंटी पाहू शकतात.",
    publicStatus: "सार्वजनिक स्थिती",
    publicStatusUpdates: "सार्वजनिक स्थिती सिंक आहे",
    quickIssueTypes: "जलद डेमो समस्या प्रकार",
    ready: "तयार",
    readyToSign: "नागरी पुरावा साइन करण्यास तयार",
    repairImageVisible: "दुरुस्ती फोटो दिसत आहे",
    repairIntegrity: "दुरुस्ती गुणवत्ता",
    repairProof: "दुरुस्ती पुरावा",
    repairSubmitted: "दुरुस्ती जमा",
    repeatFailure: "पुन्हा बिघाड",
    repeatFailureDetected: "पुन्हा बिघाड आढळला",
    repeatFailureScan: "पुन्हा बिघाड स्कॅन",
    reportIssue: "समस्या नोंदवा",
    reportIssuePlaceholder: "नागरी समस्या वर्णन करा: रस्ता, नाली, दिवे, कचरा, पाणी गळती, फुटपाथ...",
    resetDemo: "डेमो रीसेट",
    resolverReputationActive: "रिजॉल्वर प्रतिष्ठा सक्रिय",
    runAiRepairAudit: "AI दुरुस्ती ऑडिट चालवा",
    scanRepeatFailure: "पुन्हा बिघाड स्कॅन करा",
    selectedAddress: "निवडलेला पत्ता",
    selectedCase: "निवडलेला सार्वजनिक केस",
    severity: "गंभीरता",
    signAndCreate: "साइन करून तयार करा",
    status: "स्थिती",
    submitProofActivateWarranty: "पुरावा जमा करा आणि वारंटी सक्रिय करा",
    submitReport: "अहवाल जमा करा",
    syncedWarrantyRegistry: "सिंक वारंटी नोंदणी",
    systemStatus: "सिस्टम स्थिती",
    technicalObservation: "तांत्रिक निरीक्षण",
    underWarranty: "वारंटीमध्ये",
    unifiedAnalysis: "एकत्रित समस्या विश्लेषण",
    universalInfrastructureEvidence: "सार्वत्रिक इन्फ्रास्ट्रक्चर पुरावा",
    uploadAfterRepairEvidence: "दुरुस्तीनंतर फोटो अपलोड करा",
    uploadAfterRepairHint: "हा फोटो सार्वजनिक पुरावा पेजवर दिसेल",
    uploadCivicEvidence: "नागरी समस्या पुरावा ड्रॅग करा",
    uploadClickBrowse: "किंवा डिव्हाइसवरून निवडा",
    urbanLedger: "शहरी लेजर",
    useCurrentGps: "माझा GPS वापरा",
    verifiedRepairs: "सत्यापित दुरुस्ती",
    viewContract: "कॉन्ट्रॅक्ट पहा",
    viewOnCommandCenter: "कमांड सेंटरमध्ये पहा",
    walletReady: "वॉलेट तयार",
    ward: "वार्ड",
    warranty: "वारंटी",
    warrantyActivated: "वारंटी सक्रिय",
    warrantyGuard: "वारंटी गार्ड",
    warrantyOracleListening: "वारंटी ऑरेकल ऐकत आहे",
    warrantyScanner: "वारंटी स्कॅनर",
    warrantyStateVisible: "वारंटी स्थिती नागरिकांना दिसते",
    warrantyWatch: "वारंटी निरीक्षण",
    signUp: "साइन अप",
    login: "लॉगिन",
    dashboard: "डॅशबोर्ड",
    roleBasedAccess: "भूमिका-आधारित प्रवेश",
    verifyPersonBeforeProof: "पुराव्यापूर्वी व्यक्तीची पडताळणी करा.",
    authPageSubtitle: "नागरिक, कंत्राटदार आणि वार्ड एडमिनला वेगळे डॅशबोर्ड मिळतात. प्रत्येक प्रोफाइलला प्रूफ हॅश मिळतो.",
    enterEmailOtp: "ईमेल OTP टाका",
    createCityPraamanProfile: "CityPramaan प्रोफाइल तयार करा",
    welcomeBack: "पुन्हा स्वागत",
    codeSentTo: "कोड पाठवला",
    signingUpAs: "साइन अप होत आहे",
    loginWithEmail: "नोंदणीकृत ईमेल आणि पासवर्डने लॉगिन करा.",
    fullName: "पूर्ण नाव",
    contactNumber: "संपर्क क्रमांक",
    contractorIdentityArea: "कंत्राटदार ओळख आणि सेवा क्षेत्र",
    contractorIdNo: "कंत्राटदार ID / ओळख क्रमांक",
    companyAgency: "कंपनी / एजन्सी",
    assignedAreaLocality: "नियुक्त क्षेत्र / परिसर",
    assignedWardZone: "नियुक्त वार्ड / झोन",
    workCategorySpecialization: "कार्य श्रेणी / विशेषता",
    verificationEmail: "पडताळणी ईमेल",
    otpCode: "OTP कोड",
    resendCode: "कोड पुन्हा पाठवा",
    emailAddress: "ईमेल पत्ता",
    password: "पासवर्ड",
    processing: "प्रक्रिया होत आहे...",
    verifyEmail: "ईमेल पडताळा",
    createAccount: "खाते तयार करा",
    verificationEmailSent: "पडताळणी ईमेल पाठवला.",
    verificationEmailSentAgain: "पडताळणी ईमेल पुन्हा पाठवला.",
    authFailed: "प्रमाणीकरण अयशस्वी.",
    couldNotResend: "पडताळणी कोड पुन्हा पाठवता आला नाही.",
    roleUserDetail: "नागरिक समस्या नोंदवा आणि सार्वजनिक पुरावा ट्रॅक करा.",
    roleAdminDetail: "वार्ड अहवाल, मंजुरी आणि वारंटी केसेसची समीक्षा करा.",
    roleContractorDetail: "ओळख, क्षेत्र, श्रेणी नोंदवा आणि दुरुस्ती पुरावा सादर करा.",
    roadRepair: "रस्ता दुरुस्ती",
    drainage: "नाली",
    streetlight: "पथदीप",
    garbageCleanup: "कचरा स्वच्छता",
    waterLeakage: "पाणी गळती",
    footpathRepair: "फुटपाथ दुरुस्ती",
    powerOutage: "वीज खंडित",
    generalCivicRepair: "सामान्य नागरी दुरुस्ती",
  },
  bn: {
    about: "সম্পর্কে",
    accountabilityImpact: "জবাবদিহির প্রভাব",
    active: "সক্রিয়",
    activeReports: "সক্রিয় রিপোর্ট",
    afterRepairProofAttached: "মেরামতের পরের প্রমাণ যুক্ত",
    aiClassifierOnline: "AI শ্রেণিবিন্যাস চালু",
    aiConfidence: "AI আস্থা",
    aiDiagnosticsVerdict: "AI নির্ণয় ফলাফল",
    aiIssueBrain: "AI সমস্যা ইঞ্জিন",
    aiPreVerification: "AI প্রাক-যাচাই",
    aiRepairAudit: "AI মেরামত অডিট",
    aiVerdict: "AI সিদ্ধান্ত",
    analyzeIssue: "অবকাঠামো সমস্যা বিশ্লেষণ",
    asset: "সম্পদ",
    awaitingContractorAssignment: "ঠিকাদার বরাদ্দের অপেক্ষা",
    backToCommandCenter: "কমান্ড সেন্টারে ফিরুন",
    blockchainProof: "ব্লকচেইন প্রমাণ",
    blockchainTransaction: "ব্লকচেইন লেনদেন",
    chainStatus: "চেইন অবস্থা",
    city: "শহর",
    cityCoverage: "ডেমো শহর কভারেজ",
    citizenIdentity: "নাগরিক পরিচয়",
    citizenIssueBefore: "নাগরিক সমস্যা ছবি",
    citizenNode: "নাগরিক নোড",
    citizenReport: "নাগরিক রিপোর্ট",
    citizenWallet: "নাগরিক ওয়ালেট",
    commandCenter: "কমান্ড সেন্টার",
    commandCenterSubtitle: "কমান্ড সেন্টার | বহু-শহর প্রমাণ নেটওয়ার্ক",
    connectWallet: "ওয়ালেট যুক্ত করুন",
    contractor: "ঠিকাদার",
    contractorAudit: "ঠিকাদার অডিট",
    contractorProofAfter: "মেরামতের পর ঠিকাদার প্রমাণ",
    contractorRepairAudit: "ঠিকাদার মেরামত অডিট",
    contractorRepairProofLinked: "ঠিকাদার মেরামত প্রমাণ রিপোর্ট ID-তে যুক্ত",
    contractorView: "ঠিকাদার দৃশ্য",
    createProof: "ব্লকচেইন প্রমাণ তৈরি করুন",
    demoMode: "ডেমো মোড",
    documentation: "ডকুমেন্টেশন",
    duplicateRisk: "ডুপ্লিকেট ঝুঁকি",
    evidenceComparison: "প্রমাণ তুলনা",
    exactPublicLocation: "সঠিক জনসমক্ষে স্থান",
    failureTracked: "ব্যর্থতা ট্র্যাক হয়েছে",
    filingNode: "ফাইলিং নোড",
    geoMatch: "অবস্থান মিল",
    governance: "শাসন",
    hashAnchored: "হ্যাশ অ্যাঙ্কর",
    highPriority: "উচ্চ অগ্রাধিকার",
    issueBefore: "নাগরিক সমস্যা ছবি",
    issueImageVisible: "সমস্যার ছবি দেখা যাচ্ছে",
    language: "ভাষা",
    latestCitizenReport: "সর্বশেষ নাগরিক রিপোর্ট",
    liveCivicStream: "লাইভ নাগরিক স্ট্রিম",
    mapLocation: "গুগল ম্যাপ অবস্থান",
    mapLocationSubtitle: "সঠিক স্থান পিন করতে GPS বা স্থানাঙ্ক দিন।",
    manualCoordinates: "ম্যানুয়াল স্থানাঙ্ক",
    newProof: "নতুন প্রমাণ",
    newProofCreated: "নতুন প্রমাণ তৈরি",
    noRepairProofYet: "এখনও মেরামত প্রমাণ নেই",
    nodeSynced: "নোড সিঙ্ক হয়েছে",
    notActive: "সক্রিয় নয়",
    notJustReporting: "শুধু রিপোর্ট নয়",
    notJustReportingText: "ব্লকচেইন-সমর্থিত ওয়ারেন্টি যাচাই জনসমক্ষে প্রমাণসহ পুনরায় হওয়া সমস্যা ঠিক করায় সাহায্য করে।",
    onChainProofs: "অন-চেইন প্রমাণ",
    oneReportFlow: "এক রিপোর্ট প্রবাহ",
    openGoogleMaps: "গুগল ম্যাপ খুলুন",
    openIssues: "খোলা সমস্যা",
    openPublicProof: "জনসমক্ষে প্রমাণ খুলুন",
    openWarrantyRegistry: "ওয়ারেন্টি রেজিস্ট্রি খুলুন",
    pending: "অপেক্ষমাণ",
    pendingProof: "প্রমাণ অপেক্ষমাণ",
    proofEventsIndexed: "প্রমাণ ঘটনা ইনডেক্স",
    proofTimeline: "প্রমাণ টাইমলাইন",
    publicAudit: "জনসমক্ষে অডিট",
    publicCase: "জনসমক্ষে কেস",
    publicEvidenceState: "জনসমক্ষে প্রমাণ অবস্থা",
    publicHash: "জনসমক্ষে হ্যাশ",
    publicIssueHistory: "জনসমক্ষে সমস্যা ইতিহাস",
    publicLedgerReady: "জনসমক্ষে লেজার প্রস্তুত",
    publicProof: "জনসমক্ষে প্রমাণ",
    publicProofTimeline: "জনসমক্ষে প্রমাণ টাইমলাইন",
    publicRegistry: "জনসমক্ষে ওয়ারেন্টি রেজিস্ট্রি",
    publicRegistrySubtitle: "নাগরিকরা প্রতিটি রিপোর্ট, অপেক্ষমাণ মেরামত, ঠিকাদার প্রমাণ এবং সক্রিয় ওয়ারেন্টি দেখতে পারেন।",
    publicStatus: "জনসমক্ষে অবস্থা",
    publicStatusUpdates: "জনসমক্ষে অবস্থা সিঙ্ক",
    quickIssueTypes: "দ্রুত ডেমো সমস্যা ধরন",
    ready: "প্রস্তুত",
    readyToSign: "নাগরিক প্রমাণ রেকর্ড সাইন করতে প্রস্তুত",
    repairImageVisible: "মেরামত ছবি দেখা যাচ্ছে",
    repairIntegrity: "মেরামত মান",
    repairProof: "মেরামত প্রমাণ",
    repairSubmitted: "মেরামত জমা",
    repeatFailure: "পুনরায় ব্যর্থতা",
    repeatFailureDetected: "পুনরায় ব্যর্থতা শনাক্ত",
    repeatFailureScan: "পুনরায় ব্যর্থতা স্ক্যান",
    reportIssue: "সমস্যা রিপোর্ট করুন",
    reportIssuePlaceholder: "যে কোনও নাগরিক অবকাঠামো সমস্যা লিখুন: রাস্তা, নালা, স্ট্রিটলাইট, আবর্জনা, জল লিকেজ, ফুটপাত...",
    resetDemo: "ডেমো রিসেট",
    resolverReputationActive: "সমাধানকারী সুনাম সক্রিয়",
    runAiRepairAudit: "AI মেরামত অডিট চালান",
    scanRepeatFailure: "পুনরায় ব্যর্থতা স্ক্যান করুন",
    selectedAddress: "নির্বাচিত ঠিকানা",
    selectedCase: "নির্বাচিত জনসমক্ষে কেস",
    severity: "গুরুত্ব",
    signAndCreate: "সাইন করে তৈরি করুন",
    status: "অবস্থা",
    submitProofActivateWarranty: "প্রমাণ জমা দিন ও ওয়ারেন্টি সক্রিয় করুন",
    submitReport: "রিপোর্ট জমা দিন",
    syncedWarrantyRegistry: "সিঙ্ক ওয়ারেন্টি রেজিস্ট্রি",
    systemStatus: "সিস্টেম অবস্থা",
    technicalObservation: "প্রযুক্তিগত পর্যবেক্ষণ",
    underWarranty: "ওয়ারেন্টির অধীনে",
    unifiedAnalysis: "একীভূত সমস্যা বিশ্লেষণ",
    universalInfrastructureEvidence: "সার্বজনীন অবকাঠামো প্রমাণ",
    uploadAfterRepairEvidence: "মেরামতের পর ছবি আপলোড করুন",
    uploadAfterRepairHint: "এই ছবি জনসমক্ষে প্রমাণ পেজে দেখা যাবে",
    uploadCivicEvidence: "নাগরিক সমস্যা প্রমাণ টেনে ছাড়ুন",
    uploadClickBrowse: "অথবা ডিভাইস থেকে বাছতে ক্লিক করুন",
    urbanLedger: "শহর লেজার",
    useCurrentGps: "বর্তমান GPS ব্যবহার করুন",
    verifiedRepairs: "যাচাইকৃত মেরামত",
    viewContract: "কন্ট্রাক্ট দেখুন",
    viewOnCommandCenter: "কমান্ড সেন্টারে দেখুন",
    walletReady: "ওয়ালেট প্রস্তুত",
    ward: "ওয়ার্ড",
    warranty: "ওয়ারেন্টি",
    warrantyActivated: "ওয়ারেন্টি সক্রিয়",
    warrantyGuard: "ওয়ারেন্টি গার্ড",
    warrantyOracleListening: "ওয়ারেন্টি ওরাকল শুনছে",
    warrantyScanner: "ওয়ারেন্টি স্ক্যানার",
    warrantyStateVisible: "ওয়ারেন্টি অবস্থা নাগরিকদের দৃশ্যমান",
    warrantyWatch: "ওয়ারেন্টি নজরদারি",
    signUp: "সাইন আপ",
    login: "লগইন",
    dashboard: "ড্যাশবোর্ড",
    roleBasedAccess: "ভূমিকা-ভিত্তিক অ্যাক্সেস",
    verifyPersonBeforeProof: "প্রমাণের আগে ব্যক্তি যাচাই করুন।",
    authPageSubtitle: "নাগরিক, ঠিকাদার ও ওয়ার্ড অ্যাডমিন আলাদা ড্যাশবোর্ড পান। প্রতিটি প্রোফাইলে একটি প্রুফ হ্যাশ থাকে।",
    enterEmailOtp: "ইমেইল OTP দিন",
    createCityPraamanProfile: "CityPramaan প্রোফাইল তৈরি করুন",
    welcomeBack: "ফিরে আসুন",
    codeSentTo: "কোড পাঠানো হয়েছে",
    signingUpAs: "সাইন আপ হচ্ছে",
    loginWithEmail: "নিবন্ধিত ইমেইল ও পাসওয়ার্ড দিয়ে লগইন করুন।",
    fullName: "পুরো নাম",
    contactNumber: "যোগাযোগ নম্বর",
    contractorIdentityArea: "ঠিকাদার পরিচয় ও সেবা এলাকা",
    contractorIdNo: "ঠিকাদার ID / পরিচয় নম্বর",
    companyAgency: "কোম্পানি / এজেন্সি",
    assignedAreaLocality: "নির্ধারিত এলাকা / এলাকা",
    assignedWardZone: "নির্ধারিত ওয়ার্ড / জোন",
    workCategorySpecialization: "কাজের বিভাগ / বিশেষত্ব",
    verificationEmail: "যাচাই ইমেইল",
    otpCode: "OTP কোড",
    resendCode: "কোড আবার পাঠান",
    emailAddress: "ইমেইল ঠিকানা",
    password: "পাসওয়ার্ড",
    processing: "প্রক্রিয়া হচ্ছে...",
    verifyEmail: "ইমেইল যাচাই করুন",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    verificationEmailSent: "যাচাই ইমেইল পাঠানো হয়েছে।",
    verificationEmailSentAgain: "যাচাই ইমেইল আবার পাঠানো হয়েছে।",
    authFailed: "প্রমাণীকরণ ব্যর্থ।",
    couldNotResend: "যাচাই কোড পুনরায় পাঠানো যায়নি।",
    roleUserDetail: "নাগরিক সমস্যা রিপোর্ট করুন এবং প্রকাশ্য প্রমাণ ট্র্যাক করুন।",
    roleAdminDetail: "ওয়ার্ড রিপোর্ট, অনুমোদন ও ওয়ারেন্টি কেস পর্যালোচনা করুন।",
    roleContractorDetail: "পরিচয়, এলাকা, বিভাগ নিবন্ধন করুন ও মেরামত প্রমাণ জমা দিন।",
    roadRepair: "রাস্তা মেরামত",
    drainage: "ড্রেনেজ",
    streetlight: "স্ট্রিটলাইট",
    garbageCleanup: "আবর্জনা পরিষ্কার",
    waterLeakage: "জল লিকেজ",
    footpathRepair: "ফুটপাত মেরামত",
    powerOutage: "বিদ্যুৎ বিভ্রাট",
    generalCivicRepair: "সাধারণ নাগরিক মেরামত",
  },
  ta: {
    about: "பற்றி",
    accountabilityImpact: "பொறுப்புத் தாக்கம்",
    active: "செயலில்",
    activeReports: "செயலில் உள்ள புகார்கள்",
    afterRepairProofAttached: "பழுது பின் ஆதாரம் இணைக்கப்பட்டது",
    aiClassifierOnline: "AI வகைப்படுத்தல் இயங்குகிறது",
    aiConfidence: "AI நம்பிக்கை",
    aiDiagnosticsVerdict: "AI ஆய்வு முடிவு",
    aiIssueBrain: "AI பிரச்சனை இயந்திரம்",
    aiPreVerification: "AI முன் சரிபார்ப்பு",
    aiRepairAudit: "AI பழுது ஆய்வு",
    aiVerdict: "AI தீர்ப்பு",
    analyzeIssue: "உள்கட்டமைப்பு பிரச்சனை ஆய்வு",
    asset: "சொத்து",
    awaitingContractorAssignment: "ஒப்பந்ததாரர் ஒதுக்கீடு காத்திருக்கிறது",
    backToCommandCenter: "கட்டளை மையத்துக்கு திரும்பு",
    blockchainProof: "பிளாக்செயின் ஆதாரம்",
    blockchainTransaction: "பிளாக்செயின் பரிவர்த்தனை",
    chainStatus: "செயின் நிலை",
    city: "நகரம்",
    cityCoverage: "டெமோ நகர கவரேஜ்",
    citizenIdentity: "குடிமகன் அடையாளம்",
    citizenIssueBefore: "குடிமகன் பிரச்சனை படம்",
    citizenNode: "குடிமகன் நோடு",
    citizenReport: "குடிமகன் புகார்",
    citizenWallet: "குடிமகன் வாலெட்",
    commandCenter: "கட்டளை மையம்",
    commandCenterSubtitle: "கட்டளை மையம் | பல நகர ஆதார நெட்வொர்க்",
    connectWallet: "வாலெட் இணை",
    contractor: "ஒப்பந்ததாரர்",
    contractorAudit: "ஒப்பந்ததாரர் ஆய்வு",
    contractorProofAfter: "பழுது பின் ஒப்பந்ததாரர் ஆதாரம்",
    contractorRepairAudit: "ஒப்பந்ததாரர் பழுது ஆய்வு",
    contractorRepairProofLinked: "ஒப்பந்ததாரர் ஆதாரம் புகார் ID-க்கு இணைக்கப்பட்டது",
    contractorView: "ஒப்பந்ததாரர் பார்வை",
    createProof: "பிளாக்செயின் ஆதாரம் உருவாக்கு",
    demoMode: "டெமோ முறை",
    documentation: "ஆவணம்",
    duplicateRisk: "நகல் அபாயம்",
    evidenceComparison: "ஆதாரம் ஒப்பீடு",
    exactPublicLocation: "சரியான பொது இடம்",
    failureTracked: "தோல்வி கண்காணிப்பு",
    filingNode: "பதிவு நோடு",
    geoMatch: "இட பொருத்தம்",
    governance: "ஆட்சி",
    hashAnchored: "ஹாஷ் பதிக்கப்பட்டது",
    highPriority: "உயர் முன்னுரிமை",
    issueBefore: "குடிமகன் பிரச்சனை படம்",
    issueImageVisible: "பிரச்சனை படம் தெரியும்",
    language: "மொழி",
    latestCitizenReport: "சமீபத்திய குடிமகன் புகார்",
    liveCivicStream: "நேரடி குடிமை ஓட்டம்",
    mapLocation: "கூகுள் மேப் இடம்",
    mapLocationSubtitle: "சரியான இடத்தைக் குறிக்க GPS அல்லது கோஆர்டினேட் கொடுங்கள்.",
    manualCoordinates: "கையேடு கோஆர்டினேட்",
    newProof: "புதிய ஆதாரம்",
    newProofCreated: "புதிய ஆதாரம் உருவானது",
    noRepairProofYet: "இன்னும் பழுது ஆதாரம் இல்லை",
    nodeSynced: "நோடு ஒத்திசைந்தது",
    notActive: "செயலில் இல்லை",
    notJustReporting: "வெறும் புகார் அல்ல",
    notJustReportingText: "பிளாக்செயின் வாரண்டி சரிபார்ப்பு பொது ஆதாரத்துடன் மீண்டும் வரும் பிரச்சனைகளை சரிசெய்ய உதவும்.",
    onChainProofs: "ஆன்-செயின் ஆதாரங்கள்",
    oneReportFlow: "ஒரு புகார் ஓட்டம்",
    openGoogleMaps: "கூகுள் மேப் திற",
    openIssues: "திறந்த பிரச்சனைகள்",
    openPublicProof: "பொது ஆதாரம் திற",
    openWarrantyRegistry: "வாரண்டி பதிவு திற",
    pending: "நிலுவை",
    pendingProof: "ஆதாரம் நிலுவை",
    proofEventsIndexed: "ஆதார நிகழ்வுகள் குறியிடப்பட்டது",
    proofTimeline: "ஆதார காலவரிசை",
    publicAudit: "பொது ஆய்வு",
    publicCase: "பொது வழக்கு",
    publicEvidenceState: "பொது ஆதார நிலை",
    publicHash: "பொது ஹாஷ்",
    publicIssueHistory: "பொது பிரச்சனை வரலாறு",
    publicLedgerReady: "பொது லெட்ஜர் தயார்",
    publicProof: "பொது ஆதாரம்",
    publicProofTimeline: "பொது ஆதார காலவரிசை",
    publicRegistry: "பொது வாரண்டி பதிவு",
    publicRegistrySubtitle: "ஒவ்வொரு புகார், நிலுவை பழுது, ஒப்பந்ததாரர் ஆதாரம் மற்றும் செயலில் உள்ள வாரண்டி குடிமக்களுக்கு தெரியும்.",
    publicStatus: "பொது நிலை",
    publicStatusUpdates: "பொது நிலை ஒத்திசைந்தது",
    quickIssueTypes: "விரைவு டெமோ பிரச்சனை வகைகள்",
    ready: "தயார்",
    readyToSign: "குடிமை ஆதார பதிவை கையொப்பமிட தயார்",
    repairImageVisible: "பழுது படம் தெரியும்",
    repairIntegrity: "பழுது தரம்",
    repairProof: "பழுது ஆதாரம்",
    repairSubmitted: "பழுது சமர்ப்பிக்கப்பட்டது",
    repeatFailure: "மீண்டும் தோல்வி",
    repeatFailureDetected: "மீண்டும் தோல்வி கண்டறியப்பட்டது",
    repeatFailureScan: "மீண்டும் தோல்வி ஸ்கேன்",
    reportIssue: "பிரச்சனை தெரிவி",
    reportIssuePlaceholder: "சாலை, வடிகால், தெருவிளக்கு, குப்பை, நீர் கசிவு, நடைபாதை போன்ற பிரச்சனையை விவரிக்கவும்...",
    resetDemo: "டெமோ மீட்டமை",
    resolverReputationActive: "தீர்வு மதிப்பு செயலில்",
    runAiRepairAudit: "AI பழுது ஆய்வு இயக்கு",
    scanRepeatFailure: "மீண்டும் தோல்வி ஸ்கேன் செய்",
    selectedAddress: "தேர்ந்தெடுத்த முகவரி",
    selectedCase: "தேர்ந்தெடுத்த பொது வழக்கு",
    severity: "கடுமை",
    signAndCreate: "கையொப்பமிட்டு உருவாக்கு",
    status: "நிலை",
    submitProofActivateWarranty: "ஆதாரம் சமர்ப்பித்து வாரண்டி செயலில் செய்",
    submitReport: "புகார் சமர்ப்பி",
    syncedWarrantyRegistry: "ஒத்திசைந்த வாரண்டி பதிவு",
    systemStatus: "அமைப்பு நிலை",
    technicalObservation: "தொழில்நுட்ப குறிப்புகள்",
    underWarranty: "வாரண்டியில்",
    unifiedAnalysis: "ஒற்றை பிரச்சனை ஆய்வு",
    universalInfrastructureEvidence: "பொது உள்கட்டமைப்பு ஆதாரம்",
    uploadAfterRepairEvidence: "பழுது பின் படம் பதிவேற்று",
    uploadAfterRepairHint: "இந்த படம் பொது ஆதார பக்கத்தில் தெரியும்",
    uploadCivicEvidence: "குடிமை பிரச்சனை ஆதாரத்தை இழுத்து விடவும்",
    uploadClickBrowse: "அல்லது சாதனத்தில் இருந்து தேர்வு செய்ய கிளிக் செய்",
    urbanLedger: "நகர லெட்ஜர்",
    useCurrentGps: "தற்போதைய GPS பயன்படுத்து",
    verifiedRepairs: "சரிபார்க்கப்பட்ட பழுது",
    viewContract: "கான்ட்ராக்ட் பார்க்க",
    viewOnCommandCenter: "கட்டளை மையத்தில் பார்க்க",
    walletReady: "வாலெட் தயார்",
    ward: "வார்டு",
    warranty: "வாரண்டி",
    warrantyActivated: "வாரண்டி செயலில்",
    warrantyGuard: "வாரண்டி காவல்",
    warrantyOracleListening: "வாரண்டி ஓரக்கிள் கேட்கிறது",
    warrantyScanner: "வாரண்டி ஸ்கேனர்",
    warrantyStateVisible: "வாரண்டி நிலை குடிமக்களுக்கு தெரியும்",
    warrantyWatch: "வாரண்டி கண்காணிப்பு",
    signUp: "பதிவு செய்",
    login: "உள்நுழை",
    dashboard: "டாஷ்போர்டு",
    roleBasedAccess: "பங்கு அடிப்படையிலான அணுகல்",
    verifyPersonBeforeProof: "ஆதாரத்திற்கு முன் நபரை சரிபார்க்கவும்.",
    authPageSubtitle: "குடிமக்கள், ஒப்பந்ததாரர்கள் மற்றும் வார்டு நிர்வாகிகளுக்கு வேறுவேறு டாஷ்போர்டுகள் உள்ளன.",
    enterEmailOtp: "மின்னஞ்சல் OTP உள்ளிடுக",
    createCityPraamanProfile: "CityPramaan சுயவிவரம் உருவாக்கு",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    codeSentTo: "குறியீடு அனுப்பப்பட்டது",
    signingUpAs: "பதிவு செய்கிறது",
    loginWithEmail: "பதிவு செய்த மின்னஞ்சல் மற்றும் கடவுச்சொல்லுடன் உள்நுழையுங்கள்.",
    fullName: "முழு பெயர்",
    contactNumber: "தொடர்பு எண்",
    contractorIdentityArea: "ஒப்பந்ததாரர் அடையாளம் மற்றும் சேவை பகுதி",
    contractorIdNo: "ஒப்பந்ததாரர் ID / அடையாள எண்",
    companyAgency: "நிறுவனம் / நிறுவனம்",
    assignedAreaLocality: "ஒதுக்கப்பட்ட பகுதி / இடம்",
    assignedWardZone: "ஒதுக்கப்பட்ட வார்டு / மண்டலம்",
    workCategorySpecialization: "வேலை வகை / சிறப்பு",
    verificationEmail: "சரிபார்ப்பு மின்னஞ்சல்",
    otpCode: "OTP குறியீடு",
    resendCode: "குறியீடு மீண்டும் அனுப்பு",
    emailAddress: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    processing: "செயலாக்கப்படுகிறது...",
    verifyEmail: "மின்னஞ்சல் சரிபார்",
    createAccount: "கணக்கு உருவாக்கு",
    verificationEmailSent: "சரிபார்ப்பு மின்னஞ்சல் அனுப்பப்பட்டது.",
    verificationEmailSentAgain: "சரிபார்ப்பு மின்னஞ்சல் மீண்டும் அனுப்பப்பட்டது.",
    authFailed: "அங்கீகாரம் தோல்வி.",
    couldNotResend: "சரிபார்ப்பு குறியீட்டை மீண்டும் அனுப்ப முடியவில்லை.",
    roleUserDetail: "குடிமக்கள் பிரச்சனைகளை தெரிவித்து பொது ஆதாரத்தை கண்காணிக்கவும்.",
    roleAdminDetail: "வார்டு அறிக்கைகள், ஒப்புதல்கள் மற்றும் வாரண்டி வழக்குகளை மதிப்பாய்வு செய்யுங்கள்.",
    roleContractorDetail: "அடையாளம், பகுதி, வகை பதிவு செய்து பழுது ஆதாரம் சமர்பிக்கவும்.",
    roadRepair: "சாலை பழுது",
    drainage: "வடிகால்",
    streetlight: "தெரு விளக்கு",
    garbageCleanup: "குப்பை சுத்தம்",
    waterLeakage: "நீர் கசிவு",
    footpathRepair: "நடைபாதை பழுது",
    powerOutage: "மின் தடை",
    generalCivicRepair: "பொது நகரப் பழுது",
  },
  te: {
    about: "గురించి",
    accountabilityImpact: "బాధ్యత ప్రభావం",
    active: "యాక్టివ్",
    activeReports: "యాక్టివ్ రిపోర్టులు",
    afterRepairProofAttached: "మరమ్మత్తు తర్వాత ప్రూఫ్ జతచేయబడింది",
    aiClassifierOnline: "AI వర్గీకరణ ఆన్‌లైన్",
    aiConfidence: "AI నమ్మకం",
    aiDiagnosticsVerdict: "AI నిర్ధారణ ఫలితం",
    aiIssueBrain: "AI సమస్య ఇంజిన్",
    aiPreVerification: "AI ముందస్తు ధృవీకరణ",
    aiRepairAudit: "AI మరమ్మత్తు ఆడిట్",
    aiVerdict: "AI తీర్పు",
    analyzeIssue: "ఇన్‌ఫ్రాస్ట్రక్చర్ సమస్య విశ్లేషణ",
    asset: "ఆస్తి",
    awaitingContractorAssignment: "కాంట్రాక్టర్ కేటాయింపు కోసం వేచి ఉంది",
    backToCommandCenter: "కమాండ్ సెంటర్‌కు తిరిగి",
    blockchainProof: "బ్లాక్‌చెయిన్ ప్రూఫ్",
    blockchainTransaction: "బ్లాక్‌చెయిన్ లావాదేవీ",
    chainStatus: "చైన్ స్థితి",
    city: "నగరం",
    cityCoverage: "డెమో నగర కవరేజ్",
    citizenIdentity: "పౌర గుర్తింపు",
    citizenIssueBefore: "పౌర సమస్య చిత్రం",
    citizenNode: "పౌర నోడ్",
    citizenReport: "పౌర రిపోర్ట్",
    citizenWallet: "పౌర వాలెట్",
    commandCenter: "కమాండ్ సెంటర్",
    commandCenterSubtitle: "కమాండ్ సెంటర్ | బహుళ నగర ప్రూఫ్ నెట్‌వర్క్",
    connectWallet: "వాలెట్ కనెక్ట్ చేయండి",
    contractor: "కాంట్రాక్టర్",
    contractorAudit: "కాంట్రాక్టర్ ఆడిట్",
    contractorProofAfter: "మరమ్మత్తు తర్వాత కాంట్రాక్టర్ ప్రూఫ్",
    contractorRepairAudit: "కాంట్రాక్టర్ మరమ్మత్తు ఆడిట్",
    contractorRepairProofLinked: "కాంట్రాక్టర్ ప్రూఫ్ రిపోర్ట్ ID కు లింక్ అయింది",
    contractorView: "కాంట్రాక్టర్ వీక్షణ",
    createProof: "బ్లాక్‌చెయిన్ ప్రూఫ్ సృష్టించండి",
    demoMode: "డెమో మోడ్",
    documentation: "డాక్యుమెంటేషన్",
    duplicateRisk: "డూప్లికేట్ ప్రమాదం",
    evidenceComparison: "ప్రూఫ్ పోలిక",
    exactPublicLocation: "ఖచ్చితమైన ప్రజా స్థానం",
    failureTracked: "విఫలం ట్రాక్ అయింది",
    filingNode: "ఫైలింగ్ నోడ్",
    geoMatch: "స్థానం సరిపోలిక",
    governance: "పాలన",
    hashAnchored: "హ్యాష్ యాంకర్",
    highPriority: "అధిక ప్రాధాన్యం",
    issueBefore: "పౌర సమస్య చిత్రం",
    issueImageVisible: "సమస్య చిత్రం కనిపిస్తుంది",
    language: "భాష",
    latestCitizenReport: "తాజా పౌర రిపోర్ట్",
    liveCivicStream: "లైవ్ పౌర ప్రవాహం",
    mapLocation: "గూగుల్ మ్యాప్ స్థానం",
    mapLocationSubtitle: "ఖచ్చితమైన స్థానాన్ని పిన్ చేయడానికి GPS లేదా కోఆర్డినేట్లు ఇవ్వండి.",
    manualCoordinates: "మాన్యువల్ కోఆర్డినేట్లు",
    newProof: "కొత్త ప్రూఫ్",
    newProofCreated: "కొత్త ప్రూఫ్ సృష్టించబడింది",
    noRepairProofYet: "ఇంకా మరమ్మత్తు ప్రూఫ్ లేదు",
    nodeSynced: "నోడ్ సింక్ అయింది",
    notActive: "యాక్టివ్ కాదు",
    notJustReporting: "కేవలం రిపోర్టింగ్ కాదు",
    notJustReportingText: "బ్లాక్‌చెయిన్ వారంటీ ధృవీకరణ ప్రజా ప్రూఫ్‌తో మళ్లీ వచ్చే సమస్యలు సరిచేయడంలో సహాయపడుతుంది.",
    onChainProofs: "ఆన్-చెయిన్ ప్రూఫ్‌లు",
    oneReportFlow: "ఒక రిపోర్ట్ ప్రవాహం",
    openGoogleMaps: "గూగుల్ మ్యాప్ తెరవండి",
    openIssues: "తెరిచి ఉన్న సమస్యలు",
    openPublicProof: "ప్రజా ప్రూఫ్ తెరవండి",
    openWarrantyRegistry: "వారంటీ రిజిస్ట్రీ తెరవండి",
    pending: "పెండింగ్",
    pendingProof: "ప్రూఫ్ పెండింగ్",
    proofEventsIndexed: "ప్రూఫ్ సంఘటనలు ఇండెక్స్ అయ్యాయి",
    proofTimeline: "ప్రూఫ్ టైమ్‌లైన్",
    publicAudit: "ప్రజా ఆడిట్",
    publicCase: "ప్రజా కేసు",
    publicEvidenceState: "ప్రజా ప్రూఫ్ స్థితి",
    publicHash: "ప్రజా హ్యాష్",
    publicIssueHistory: "ప్రజా సమస్య చరిత్ర",
    publicLedgerReady: "ప్రజా లెడ్జర్ సిద్ధం",
    publicProof: "ప్రజా ప్రూఫ్",
    publicProofTimeline: "ప్రజా ప్రూఫ్ టైమ్‌లైన్",
    publicRegistry: "ప్రజా వారంటీ రిజిస్ట్రీ",
    publicRegistrySubtitle: "ప్రజలు ప్రతి రిపోర్ట్, పెండింగ్ మరమ్మత్తు, కాంట్రాక్టర్ ప్రూఫ్ మరియు యాక్టివ్ వారంటీని చూడగలరు.",
    publicStatus: "ప్రజా స్థితి",
    publicStatusUpdates: "ప్రజా స్థితి సింక్ అయింది",
    quickIssueTypes: "త్వరిత డెమో సమస్య రకాలు",
    ready: "సిద్ధం",
    readyToSign: "పౌర ప్రూఫ్ రికార్డ్ సైన్ చేయడానికి సిద్ధం",
    repairImageVisible: "మరమ్మత్తు చిత్రం కనిపిస్తుంది",
    repairIntegrity: "మరమ్మత్తు నాణ్యత",
    repairProof: "మరమ్మత్తు ప్రూఫ్",
    repairSubmitted: "మరమ్మత్తు సమర్పించబడింది",
    repeatFailure: "మళ్లీ విఫలం",
    repeatFailureDetected: "మళ్లీ విఫలం గుర్తించబడింది",
    repeatFailureScan: "మళ్లీ విఫలం స్కాన్",
    reportIssue: "సమస్య రిపోర్ట్ చేయండి",
    reportIssuePlaceholder: "ఏ పౌర ఇన్‌ఫ్రాస్ట్రక్చర్ సమస్యనైనా వివరించండి: రోడ్, డ్రెయిన్, వీధి దీపం, చెత్త, నీటి లీకేజ్, ఫుట్‌పాత్...",
    resetDemo: "డెమో రీసెట్",
    resolverReputationActive: "పరిష్కారకుడి ప్రతిష్ట యాక్టివ్",
    runAiRepairAudit: "AI మరమ్మత్తు ఆడిట్ నడపండి",
    scanRepeatFailure: "మళ్లీ విఫలం స్కాన్ చేయండి",
    selectedAddress: "ఎంచుకున్న చిరునామా",
    selectedCase: "ఎంచుకున్న ప్రజా కేసు",
    severity: "తీవ్రత",
    signAndCreate: "సైన్ చేసి సృష్టించండి",
    status: "స్థితి",
    submitProofActivateWarranty: "ప్రూఫ్ సమర్పించి వారంటీ యాక్టివ్ చేయండి",
    submitReport: "రిపోర్ట్ సమర్పించండి",
    syncedWarrantyRegistry: "సింక్ వారంటీ రిజిస్ట్రీ",
    systemStatus: "సిస్టమ్ స్థితి",
    technicalObservation: "టెక్నికల్ పరిశీలన",
    underWarranty: "వారంటీలో",
    unifiedAnalysis: "ఏకీకృత సమస్య విశ్లేషణ",
    universalInfrastructureEvidence: "సార్వత్రిక ఇన్‌ఫ్రాస్ట్రక్చర్ ప్రూఫ్",
    uploadAfterRepairEvidence: "మరమ్మత్తు తర్వాత చిత్రం అప్లోడ్ చేయండి",
    uploadAfterRepairHint: "ఈ చిత్రం ప్రజా ప్రూఫ్ పేజీలో కనిపిస్తుంది",
    uploadCivicEvidence: "పౌర సమస్య ప్రూఫ్ డ్రాగ్ చేసి వదలండి",
    uploadClickBrowse: "లేదా పరికరం నుండి ఎంచడానికి క్లిక్ చేయండి",
    urbanLedger: "నగర లెడ్జర్",
    useCurrentGps: "ప్రస్తుత GPS వాడండి",
    verifiedRepairs: "ధృవీకరించిన మరమ్మత్తులు",
    viewContract: "కాంట్రాక్ట్ చూడండి",
    viewOnCommandCenter: "కమాండ్ సెంటర్‌లో చూడండి",
    walletReady: "వాలెట్ సిద్ధం",
    ward: "వార్డ్",
    warranty: "వారంటీ",
    warrantyActivated: "వారంటీ యాక్టివ్",
    warrantyGuard: "వారంటీ గార్డ్",
    warrantyOracleListening: "వారంటీ ఓరాకిల్ వినుతోంది",
    warrantyScanner: "వారంటీ స్కానర్",
    warrantyStateVisible: "వారంటీ స్థితి పౌరులకు కనిపిస్తుంది",
    warrantyWatch: "వారంటీ పర్యవేక్షణ",
    signUp: "సైన్ అప్",
    login: "లాగిన్",
    dashboard: "డాష్‌బోర్డ్",
    roleBasedAccess: "పాత్ర-ఆధారిత యాక్సెస్",
    verifyPersonBeforeProof: "ప్రూఫ్‌కు ముందు వ్యక్తిని ధృవీకరించండి.",
    authPageSubtitle: "పౌరులు, కాంట్రాక్టర్లు మరియు వార్డ్ అడ్మిన్‌లకు వేర్వేరు డాష్‌బోర్డ్‌లు ఉంటాయి.",
    enterEmailOtp: "ఇమెయిల్ OTP నమోదు చేయండి",
    createCityPraamanProfile: "CityPramaan ప్రొఫైల్ సృష్టించండి",
    welcomeBack: "తిరిగి స్వాగతం",
    codeSentTo: "కోడ్ పంపబడింది",
    signingUpAs: "సైన్ అప్ అవుతోంది",
    loginWithEmail: "నమోదిత ఇమెయిల్ మరియు పాస్‌వర్డ్‌తో లాగిన్ చేయండి.",
    fullName: "పూర్తి పేరు",
    contactNumber: "సంప్రదింపు నంబర్",
    contractorIdentityArea: "కాంట్రాక్టర్ గుర్తింపు మరియు సేవా ప్రాంతం",
    contractorIdNo: "కాంట్రాక్టర్ ID / గుర్తింపు నం.",
    companyAgency: "కంపెనీ / ఏజెన్సీ",
    assignedAreaLocality: "కేటాయించిన ప్రాంతం / లోకాలిటీ",
    assignedWardZone: "కేటాయించిన వార్డ్ / జోన్",
    workCategorySpecialization: "పని వర్గం / స్పెషలైజేషన్",
    verificationEmail: "ధృవీకరణ ఇమెయిల్",
    otpCode: "OTP కోడ్",
    resendCode: "కోడ్ మళ్లీ పంపండి",
    emailAddress: "ఇమెయిల్ చిరునామా",
    password: "పాస్‌వర్డ్",
    processing: "ప్రాసెస్ అవుతోంది...",
    verifyEmail: "ఇమెయిల్ ధృవీకరించండి",
    createAccount: "ఖాతా సృష్టించండి",
    verificationEmailSent: "ధృవీకరణ ఇమెయిల్ పంపబడింది.",
    verificationEmailSentAgain: "ధృవీకరణ ఇమెయిల్ మళ్లీ పంపబడింది.",
    authFailed: "ప్రమాణీకరణ విఫలమైంది.",
    couldNotResend: "ధృవీకరణ కోడ్ మళ్లీ పంపలేకపోయాం.",
    roleUserDetail: "పౌర సమస్యలను నివేదించి బహిరంగ ప్రూఫ్ ట్రాక్ చేయండి.",
    roleAdminDetail: "వార్డ్ రిపోర్ట్‌లు, ఆమోదాలు మరియు వారంటీ కేసులను సమీక్షించండి.",
    roleContractorDetail: "గుర్తింపు, ప్రాంతం, వర్గం నమోదు చేసి మరమ్మత్తు ప్రూఫ్ సమర్పించండి.",
    roadRepair: "రోడ్డు మరమ్మత్తు",
    drainage: "డ్రెయినేజ్",
    streetlight: "వీధి దీపం",
    garbageCleanup: "చెత్త శుభ్రపరచడం",
    waterLeakage: "నీటి లీకేజ్",
    footpathRepair: "ఫుట్‌పాత్ మరమ్మత్తు",
    powerOutage: "విద్యుత్ అంతరాయం",
    generalCivicRepair: "సాధారణ పౌర మరమ్మత్తు",
  },
  gu: {
    about: "વિશે",
    accountabilityImpact: "જવાબદારી અસર",
    active: "સક્રિય",
    activeReports: "સક્રિય રિપોર્ટ",
    afterRepairProofAttached: "રિપેર પછીનો પુરાવો જોડાયો",
    aiClassifierOnline: "AI વર્ગીકરણ ચાલુ",
    aiConfidence: "AI વિશ્વાસ",
    aiDiagnosticsVerdict: "AI નિદાન પરિણામ",
    aiIssueBrain: "AI સમસ્યા એન્જિન",
    aiPreVerification: "AI પૂર્વ ચકાસણી",
    aiRepairAudit: "AI રિપેર ઓડિટ",
    aiVerdict: "AI નિર્ણય",
    analyzeIssue: "ઇન્ફ્રાસ્ટ્રક્ચર સમસ્યા વિશ્લેષણ",
    asset: "સંપત્તિ",
    awaitingContractorAssignment: "કોન્ટ્રાક્ટર સોંપણી બાકી",
    backToCommandCenter: "કમાન્ડ સેન્ટર પર પાછા",
    blockchainProof: "બ્લોકચેઇન પુરાવો",
    blockchainTransaction: "બ્લોકચેઇન ટ્રાન્ઝેક્શન",
    chainStatus: "ચેઇન સ્થિતિ",
    city: "શહેર",
    cityCoverage: "ડેમો શહેર કવરેજ",
    citizenIdentity: "નાગરિક ઓળખ",
    citizenIssueBefore: "નાગરિક સમસ્યા ફોટો",
    citizenNode: "નાગરિક નોડ",
    citizenReport: "નાગરિક રિપોર્ટ",
    citizenWallet: "નાગરિક વૉલેટ",
    commandCenter: "કમાન્ડ સેન્ટર",
    commandCenterSubtitle: "કમાન્ડ સેન્ટર | બહુ-શહેર પુરાવા નેટવર્ક",
    connectWallet: "વૉલેટ જોડો",
    contractor: "કોન્ટ્રાક્ટર",
    contractorAudit: "કોન્ટ્રાક્ટર ઓડિટ",
    contractorProofAfter: "રિપેર પછી કોન્ટ્રાક્ટર પુરાવો",
    contractorRepairAudit: "કોન્ટ્રાક્ટર રિપેર ઓડિટ",
    contractorRepairProofLinked: "કોન્ટ્રાક્ટર પુરાવો રિપોર્ટ ID સાથે જોડાયો",
    contractorView: "કોન્ટ્રાક્ટર દૃશ્ય",
    createProof: "બ્લોકચેઇન પુરાવો બનાવો",
    demoMode: "ડેમો મોડ",
    documentation: "દસ્તાવેજ",
    duplicateRisk: "ડુપ્લિકેટ જોખમ",
    evidenceComparison: "પુરાવા સરખામણી",
    exactPublicLocation: "ચોક્કસ જાહેર સ્થાન",
    failureTracked: "નિષ્ફળતા ટ્રેક થઈ",
    filingNode: "ફાઈલિંગ નોડ",
    geoMatch: "સ્થાન મેળ",
    governance: "શાસન",
    hashAnchored: "હેશ એન્કર",
    highPriority: "ઉચ્ચ પ્રાથમિકતા",
    issueBefore: "નાગરિક સમસ્યા ફોટો",
    issueImageVisible: "સમસ્યા ફોટો દેખાય છે",
    language: "ભાષા",
    latestCitizenReport: "નવીનતમ નાગરિક રિપોર્ટ",
    liveCivicStream: "લાઇવ નાગરિક પ્રવાહ",
    mapLocation: "ગૂગલ મેપ સ્થાન",
    mapLocationSubtitle: "ચોક્કસ સ્થાન પિન કરવા GPS અથવા કોઓર્ડિનેટ દાખલ કરો.",
    manualCoordinates: "મેન્યુઅલ કોઓર્ડિનેટ",
    newProof: "નવો પુરાવો",
    newProofCreated: "નવો પુરાવો બન્યો",
    noRepairProofYet: "હજુ રિપેર પુરાવો નથી",
    nodeSynced: "નોડ સિંક થયો",
    notActive: "સક્રિય નથી",
    notJustReporting: "ફક્ત રિપોર્ટિંગ નથી",
    notJustReportingText: "બ્લોકચેઇન આધારિત વોરંટી ચકાસણી જાહેર પુરાવા સાથે ફરી આવતી સમસ્યાઓ ઠીક કરાવવામાં મદદ કરે છે.",
    onChainProofs: "ઓન-ચેઇન પુરાવા",
    oneReportFlow: "એક રિપોર્ટ પ્રવાહ",
    openGoogleMaps: "ગૂગલ મેપ ખોલો",
    openIssues: "ખુલ્લી સમસ્યાઓ",
    openPublicProof: "જાહેર પુરાવો ખોલો",
    openWarrantyRegistry: "વોરંટી રજિસ્ટ્રી ખોલો",
    pending: "બાકી",
    pendingProof: "પુરાવો બાકી",
    proofEventsIndexed: "પુરાવા ઘટના ઇન્ડેક્સ",
    proofTimeline: "પુરાવા સમયરેખા",
    publicAudit: "જાહેર ઓડિટ",
    publicCase: "જાહેર કેસ",
    publicEvidenceState: "જાહેર પુરાવા સ્થિતિ",
    publicHash: "જાહેર હેશ",
    publicIssueHistory: "જાહેર સમસ્યા ઇતિહાસ",
    publicLedgerReady: "જાહેર લેજર તૈયાર",
    publicProof: "જાહેર પુરાવો",
    publicProofTimeline: "જાહેર પુરાવા સમયરેખા",
    publicRegistry: "જાહેર વોરંટી રજિસ્ટ્રી",
    publicRegistrySubtitle: "નાગરિકો દરેક રિપોર્ટ, બાકી રિપેર, કોન્ટ્રાક્ટર પુરાવો અને સક્રિય વોરંટી જોઈ શકે છે.",
    publicStatus: "જાહેર સ્થિતિ",
    publicStatusUpdates: "જાહેર સ્થિતિ સિંક છે",
    quickIssueTypes: "ઝડપી ડેમો સમસ્યા પ્રકાર",
    ready: "તૈયાર",
    readyToSign: "નાગરિક પુરાવો રેકોર્ડ સાઇન કરવા તૈયાર",
    repairImageVisible: "રિપેર ફોટો દેખાય છે",
    repairIntegrity: "રિપેર ગુણવત્તા",
    repairProof: "રિપેર પુરાવો",
    repairSubmitted: "રિપેર સબમિટ",
    repeatFailure: "ફરી નિષ્ફળતા",
    repeatFailureDetected: "ફરી નિષ્ફળતા મળી",
    repeatFailureScan: "ફરી નિષ્ફળતા સ્કેન",
    reportIssue: "સમસ્યા રિપોર્ટ કરો",
    reportIssuePlaceholder: "કોઈપણ નાગરિક ઇન્ફ્રાસ્ટ્રક્ચર સમસ્યા વર્ણવો: રસ્તો, ડ્રેન, સ્ટ્રીટલાઇટ, કચરો, પાણી લીકેજ, ફૂટપાથ...",
    resetDemo: "ડેમો રીસેટ",
    resolverReputationActive: "રિઝોલ્વર પ્રતિષ્ઠા સક્રિય",
    runAiRepairAudit: "AI રિપેર ઓડિટ ચલાવો",
    scanRepeatFailure: "ફરી નિષ્ફળતા સ્કેન કરો",
    selectedAddress: "પસંદ કરેલ સરનામું",
    selectedCase: "પસંદ કરેલ જાહેર કેસ",
    severity: "ગંભીરતા",
    signAndCreate: "સાઇન કરીને બનાવો",
    status: "સ્થિતિ",
    submitProofActivateWarranty: "પુરાવો સબમિટ કરો અને વોરંટી સક્રિય કરો",
    submitReport: "રિપોર્ટ સબમિટ કરો",
    syncedWarrantyRegistry: "સિંક વોરંટી રજિસ્ટ્રી",
    systemStatus: "સિસ્ટમ સ્થિતિ",
    technicalObservation: "ટેકનિકલ અવલોકન",
    underWarranty: "વોરંટી હેઠળ",
    unifiedAnalysis: "એકિકૃત સમસ્યા વિશ્લેષણ",
    universalInfrastructureEvidence: "સર્વવ્યાપી ઇન્ફ્રાસ્ટ્રક્ચર પુરાવો",
    uploadAfterRepairEvidence: "રિપેર પછીનો ફોટો અપલોડ કરો",
    uploadAfterRepairHint: "આ ફોટો જાહેર પુરાવા પેજ પર દેખાશે",
    uploadCivicEvidence: "નાગરિક સમસ્યા પુરાવો ખેંચી મૂકો",
    uploadClickBrowse: "અથવા ઉપકરણમાંથી પસંદ કરવા ક્લિક કરો",
    urbanLedger: "શહેર લેજર",
    useCurrentGps: "વર્તમાન GPS વાપરો",
    verifiedRepairs: "ચકાસેલ રિપેર",
    viewContract: "કોન્ટ્રાક્ટ જુઓ",
    viewOnCommandCenter: "કમાન્ડ સેન્ટરમાં જુઓ",
    walletReady: "વૉલેટ તૈયાર",
    ward: "વોર્ડ",
    warranty: "વોરંટી",
    warrantyActivated: "વોરંટી સક્રિય",
    warrantyGuard: "વોરંટી ગાર્ડ",
    warrantyOracleListening: "વોરંટી ઓરેકલ સાંભળે છે",
    warrantyScanner: "વોરંટી સ્કેનર",
    warrantyStateVisible: "વોરંટી સ્થિતિ નાગરિકોને દેખાય છે",
    warrantyWatch: "વોરંટી દેખરેખ",
    signUp: "સાઇન અપ",
    login: "લૉગિન",
    dashboard: "ડૅશબોર્ડ",
    roleBasedAccess: "ભૂમિકા-આધારિત ઍક્સેસ",
    verifyPersonBeforeProof: "પુરાવા પહેલાં વ્યક્તિ ચકાસો.",
    authPageSubtitle: "નાગરિક, કોન્ટ્રાક્ટર અને વોર્ડ એડમિનને અલગ ડૅશબોર્ડ મળે છે.",
    enterEmailOtp: "ઇમેઇલ OTP દાખલ કરો",
    createCityPraamanProfile: "CityPramaan પ્રોફાઇલ બનાવો",
    welcomeBack: "પાછા સ્વાગત",
    codeSentTo: "કોડ મોકલ્યો",
    signingUpAs: "સાઇન અપ થઈ રહ્યું છે",
    loginWithEmail: "નોંધાયેલ ઇમેઇલ અને પાસવર્ડ વડે લૉગિન કરો.",
    fullName: "પૂરું નામ",
    contactNumber: "સંપર્ક નંબર",
    contractorIdentityArea: "કોન્ટ્રાક્ટર ઓળખ અને સેવા વિસ્તાર",
    contractorIdNo: "કોન્ટ્રાક્ટર ID / ઓળખ નં.",
    companyAgency: "કંપની / એજન્સી",
    assignedAreaLocality: "સોંપાયેલ વિસ્તાર / મહોલ્લો",
    assignedWardZone: "સોંપાયેલ વૉર્ડ / ઝોન",
    workCategorySpecialization: "કામ શ્રેણી / વિશેષતા",
    verificationEmail: "ચકાસણી ઇમેઇલ",
    otpCode: "OTP કોડ",
    resendCode: "કોડ ફરી મોકલો",
    emailAddress: "ઇમેઇલ સરનામું",
    password: "પાસવર્ડ",
    processing: "પ્રક્રિયા થઈ રહી છે...",
    verifyEmail: "ઇમેઇલ ચકાસો",
    createAccount: "ખાતું બનાવો",
    verificationEmailSent: "ચકાસણી ઇમેઇલ મોકલ્યો.",
    verificationEmailSentAgain: "ચકાસણી ઇમેઇલ ફરી મોકલ્યો.",
    authFailed: "પ્રમાણીકરણ નિષ્ફળ.",
    couldNotResend: "ચકાસણી કોડ ફરી ન મોકલી શક્યા.",
    roleUserDetail: "નાગરિક સમસ્યાઓ જાણ કરો અને જાહેર પુરાવો ટ્રૅક કરો.",
    roleAdminDetail: "વૉર્ડ રિપોર્ટ, મંજૂરી અને વૉરંટી કેસ સમીક્ષા કરો.",
    roleContractorDetail: "ઓળખ, ક્ષેત્ર, શ્રેણી નોંધો અને મરામત પુરાવો સ‌ादर કરો.",
    roadRepair: "રસ્તો દુરસ્ત",
    drainage: "ગટર",
    streetlight: "સ્ટ્રીટલાઇટ",
    garbageCleanup: "કચરો સ‌ाफ",
    waterLeakage: "પાણી લીકેજ",
    footpathRepair: "ફૂટપાથ દુરસ્ત",
    powerOutage: "વીજ કાપ",
    generalCivicRepair: "સામાન્ય નાગરિક મરામત",
  },
  kn: {
    about: "ಬಗ್ಗೆ",
    accountabilityImpact: "ಜವಾಬ್ದಾರಿ ಪರಿಣಾಮ",
    active: "ಸಕ್ರಿಯ",
    activeReports: "ಸಕ್ರಿಯ ವರದಿಗಳು",
    afterRepairProofAttached: "ದುರಸ್ತಿ ನಂತರದ ಸಾಕ್ಷಿ ಸೇರಿದೆ",
    aiClassifierOnline: "AI ವರ್ಗೀಕರಣ ಆನ್‌ಲೈನ್",
    aiConfidence: "AI ವಿಶ್ವಾಸ",
    aiDiagnosticsVerdict: "AI ನಿರ್ಣಯ ಫಲಿತಾಂಶ",
    aiIssueBrain: "AI ಸಮಸ್ಯೆ ಎಂಜಿನ್",
    aiPreVerification: "AI ಪೂರ್ವ ಪರಿಶೀಲನೆ",
    aiRepairAudit: "AI ದುರಸ್ತಿ ಆಡಿಟ್",
    aiVerdict: "AI ತೀರ್ಪು",
    analyzeIssue: "ಮೂಲಸೌಕರ್ಯ ಸಮಸ್ಯೆ ವಿಶ್ಲೇಷಣೆ",
    asset: "ಸ್ವತ್ತು",
    awaitingContractorAssignment: "ಗುತ್ತಿಗೆದಾರ ನಿಯೋಜನೆ ಬಾಕಿ",
    backToCommandCenter: "ಕಮಾಂಡ್ ಸೆಂಟರ್‌ಗೆ ಹಿಂದಿರುಗಿ",
    blockchainProof: "ಬ್ಲಾಕ್‌ಚೈನ್ ಸಾಕ್ಷಿ",
    blockchainTransaction: "ಬ್ಲಾಕ್‌ಚೈನ್ ವ್ಯವಹಾರ",
    chainStatus: "ಚೈನ್ ಸ್ಥಿತಿ",
    city: "ನಗರ",
    cityCoverage: "ಡೆಮೋ ನಗರ ವ್ಯಾಪ್ತಿ",
    citizenIdentity: "ನಾಗರಿಕ ಗುರುತು",
    citizenIssueBefore: "ನಾಗರಿಕ ಸಮಸ್ಯೆ ಚಿತ್ರ",
    citizenNode: "ನಾಗರಿಕ ನೋಡ್",
    citizenReport: "ನಾಗರಿಕ ವರದಿ",
    citizenWallet: "ನಾಗರಿಕ ವಾಲೆಟ್",
    commandCenter: "ಕಮಾಂಡ್ ಸೆಂಟರ್",
    commandCenterSubtitle: "ಕಮಾಂಡ್ ಸೆಂಟರ್ | ಬಹು-ನಗರ ಸಾಕ್ಷಿ ಜಾಲ",
    connectWallet: "ವಾಲೆಟ್ ಸಂಪರ್ಕಿಸಿ",
    contractor: "ಗುತ್ತಿಗೆದಾರ",
    contractorAudit: "ಗುತ್ತಿಗೆದಾರ ಆಡಿಟ್",
    contractorProofAfter: "ದುರಸ್ತಿ ನಂತರ ಗುತ್ತಿಗೆದಾರ ಸಾಕ್ಷಿ",
    contractorRepairAudit: "ಗುತ್ತಿಗೆದಾರ ದುರಸ್ತಿ ಆಡಿಟ್",
    contractorRepairProofLinked: "ಗುತ್ತಿಗೆದಾರ ಸಾಕ್ಷಿ ವರದಿ ID ಗೆ ಜೋಡಿಸಲಾಗಿದೆ",
    contractorView: "ಗುತ್ತಿಗೆದಾರ ದೃಶ್ಯ",
    createProof: "ಬ್ಲಾಕ್‌ಚೈನ್ ಸಾಕ್ಷಿ ರಚಿಸಿ",
    demoMode: "ಡೆಮೋ ಮೋಡ್",
    documentation: "ದಾಖಲೆ",
    duplicateRisk: "ನಕಲಿ ಅಪಾಯ",
    evidenceComparison: "ಸಾಕ್ಷಿ ಹೋಲಿಕೆ",
    exactPublicLocation: "ನಿಖರ ಸಾರ್ವಜನಿಕ ಸ್ಥಳ",
    failureTracked: "ವಿಫಲತೆ ಟ್ರ್ಯಾಕ್ ಆಗಿದೆ",
    filingNode: "ಫೈಲಿಂಗ್ ನೋಡ್",
    geoMatch: "ಸ್ಥಳ ಹೊಂದಾಣಿಕೆ",
    governance: "ಆಡಳಿತ",
    hashAnchored: "ಹ್ಯಾಶ್ ಆಂಕರ್",
    highPriority: "ಹೆಚ್ಚು ಆದ್ಯತೆ",
    issueBefore: "ನಾಗರಿಕ ಸಮಸ್ಯೆ ಚಿತ್ರ",
    issueImageVisible: "ಸಮಸ್ಯೆ ಚಿತ್ರ ಕಾಣುತ್ತಿದೆ",
    language: "ಭಾಷೆ",
    latestCitizenReport: "ಇತ್ತೀಚಿನ ನಾಗರಿಕ ವರದಿ",
    liveCivicStream: "ಲೈವ್ ನಾಗರಿಕ ಪ್ರವಾಹ",
    mapLocation: "ಗೂಗಲ್ ಮ್ಯಾಪ್ ಸ್ಥಳ",
    mapLocationSubtitle: "ನಿಖರ ಸ್ಥಳ ಪಿನ್ ಮಾಡಲು GPS ಅಥವಾ ಕೋಆರ್ಡಿನೇಟ್ ನಮೂದಿಸಿ.",
    manualCoordinates: "ಕೈಯಿಂದ ಕೋಆರ್ಡಿನೇಟ್",
    newProof: "ಹೊಸ ಸಾಕ್ಷಿ",
    newProofCreated: "ಹೊಸ ಸಾಕ್ಷಿ ರಚನೆ",
    noRepairProofYet: "ಇನ್ನೂ ದುರಸ್ತಿ ಸಾಕ್ಷಿ ಇಲ್ಲ",
    nodeSynced: "ನೋಡ್ ಸಿಂಕ್ ಆಗಿದೆ",
    notActive: "ಸಕ್ರಿಯವಲ್ಲ",
    notJustReporting: "ಕೇವಲ ವರದಿ ಅಲ್ಲ",
    notJustReportingText: "ಬ್ಲಾಕ್‌ಚೈನ್ ಆಧಾರಿತ ವಾರಂಟಿ ಪರಿಶೀಲನೆ ಸಾರ್ವಜನಿಕ ಸಾಕ್ಷಿಯೊಂದಿಗೆ ಮರುಕಳಿಸುವ ಸಮಸ್ಯೆಗಳನ್ನು ಸರಿಪಡಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    onChainProofs: "ಆನ್-ಚೈನ್ ಸಾಕ್ಷಿಗಳು",
    oneReportFlow: "ಒಂದು ವರದಿ ಪ್ರವಾಹ",
    openGoogleMaps: "ಗೂಗಲ್ ಮ್ಯಾಪ್ ತೆರೆ",
    openIssues: "ತೆರೆದ ಸಮಸ್ಯೆಗಳು",
    openPublicProof: "ಸಾರ್ವಜನಿಕ ಸಾಕ್ಷಿ ತೆರೆ",
    openWarrantyRegistry: "ವಾರಂಟಿ ನೋಂದಣಿ ತೆರೆ",
    pending: "ಬಾಕಿ",
    pendingProof: "ಸಾಕ್ಷಿ ಬಾಕಿ",
    proofEventsIndexed: "ಸಾಕ್ಷಿ ಘಟನೆಗಳು ಸೂಚ್ಯಂಕಗೊಂಡಿವೆ",
    proofTimeline: "ಸಾಕ್ಷಿ ಕಾಲರೇಖೆ",
    publicAudit: "ಸಾರ್ವಜನಿಕ ಆಡಿಟ್",
    publicCase: "ಸಾರ್ವಜನಿಕ ಪ್ರಕರಣ",
    publicEvidenceState: "ಸಾರ್ವಜನಿಕ ಸಾಕ್ಷಿ ಸ್ಥಿತಿ",
    publicHash: "ಸಾರ್ವಜನಿಕ ಹ್ಯಾಶ್",
    publicIssueHistory: "ಸಾರ್ವಜನಿಕ ಸಮಸ್ಯೆ ಇತಿಹಾಸ",
    publicLedgerReady: "ಸಾರ್ವಜನಿಕ ಲೆಡ್ಜರ್ ಸಿದ್ಧ",
    publicProof: "ಸಾರ್ವಜನಿಕ ಸಾಕ್ಷಿ",
    publicProofTimeline: "ಸಾರ್ವಜನಿಕ ಸಾಕ್ಷಿ ಕಾಲರೇಖೆ",
    publicRegistry: "ಸಾರ್ವಜನಿಕ ವಾರಂಟಿ ನೋಂದಣಿ",
    publicRegistrySubtitle: "ನಾಗರಿಕರು ಪ್ರತಿಯೊಂದು ವರದಿ, ಬಾಕಿ ದುರಸ್ತಿ, ಗುತ್ತಿಗೆದಾರ ಸಾಕ್ಷಿ ಮತ್ತು ಸಕ್ರಿಯ ವಾರಂಟಿ ನೋಡಬಹುದು.",
    publicStatus: "ಸಾರ್ವಜನಿಕ ಸ್ಥಿತಿ",
    publicStatusUpdates: "ಸಾರ್ವಜನಿಕ ಸ್ಥಿತಿ ಸಿಂಕ್ ಆಗಿದೆ",
    quickIssueTypes: "ತ್ವರಿತ ಡೆಮೋ ಸಮಸ್ಯೆ ವಿಧಗಳು",
    ready: "ಸಿದ್ಧ",
    readyToSign: "ನಾಗರಿಕ ಸಾಕ್ಷಿ ದಾಖಲೆ ಸೈನ್ ಮಾಡಲು ಸಿದ್ಧ",
    repairImageVisible: "ದುರಸ್ತಿ ಚಿತ್ರ ಕಾಣುತ್ತಿದೆ",
    repairIntegrity: "ದುರಸ್ತಿ ಗುಣಮಟ್ಟ",
    repairProof: "ದುರಸ್ತಿ ಸಾಕ್ಷಿ",
    repairSubmitted: "ದುರಸ್ತಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    repeatFailure: "ಮರು ವಿಫಲತೆ",
    repeatFailureDetected: "ಮರು ವಿಫಲತೆ ಪತ್ತೆ",
    repeatFailureScan: "ಮರು ವಿಫಲತೆ ಸ್ಕ್ಯಾನ್",
    reportIssue: "ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ",
    reportIssuePlaceholder: "ಯಾವುದೇ ನಾಗರಿಕ ಮೂಲಸೌಕರ್ಯ ಸಮಸ್ಯೆ ವಿವರಿಸಿ: ರಸ್ತೆ, ಕಾಲುವೆ, ಬೀದಿ ದೀಪ, ಕಸ, ನೀರು ಸೋರಿಕೆ, ಪಾದಚಾರಿ ದಾರಿ...",
    resetDemo: "ಡೆಮೋ ಮರುಹೊಂದಿಸಿ",
    resolverReputationActive: "ಪರಿಹಾರಕರ ಪ್ರತಿಷ್ಠೆ ಸಕ್ರಿಯ",
    runAiRepairAudit: "AI ದುರಸ್ತಿ ಆಡಿಟ್ ನಡೆಸಿ",
    scanRepeatFailure: "ಮರು ವಿಫಲತೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    selectedAddress: "ಆಯ್ಕೆ ಮಾಡಿದ ವಿಳಾಸ",
    selectedCase: "ಆಯ್ಕೆ ಮಾಡಿದ ಸಾರ್ವಜನಿಕ ಪ್ರಕರಣ",
    severity: "ಗಂಭೀರತೆ",
    signAndCreate: "ಸೈನ್ ಮಾಡಿ ರಚಿಸಿ",
    status: "ಸ್ಥಿತಿ",
    submitProofActivateWarranty: "ಸಾಕ್ಷಿ ಸಲ್ಲಿಸಿ ವಾರಂಟಿ ಸಕ್ರಿಯಗೊಳಿಸಿ",
    submitReport: "ವರದಿ ಸಲ್ಲಿಸಿ",
    syncedWarrantyRegistry: "ಸಿಂಕ್ ವಾರಂಟಿ ನೋಂದಣಿ",
    systemStatus: "ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ",
    technicalObservation: "ತಾಂತ್ರಿಕ ಗಮನಿಕೆ",
    underWarranty: "ವಾರಂಟಿಯಲ್ಲಿದೆ",
    unifiedAnalysis: "ಏಕೀಕೃತ ಸಮಸ್ಯೆ ವಿಶ್ಲೇಷಣೆ",
    universalInfrastructureEvidence: "ಸಾರ್ವತ್ರಿಕ ಮೂಲಸೌಕರ್ಯ ಸಾಕ್ಷಿ",
    uploadAfterRepairEvidence: "ದುರಸ್ತಿ ನಂತರದ ಚಿತ್ರ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    uploadAfterRepairHint: "ಈ ಚಿತ್ರ ಸಾರ್ವಜನಿಕ ಸಾಕ್ಷಿ ಪುಟದಲ್ಲಿ ಕಾಣುತ್ತದೆ",
    uploadCivicEvidence: "ನಾಗರಿಕ ಸಮಸ್ಯೆ ಸಾಕ್ಷಿಯನ್ನು ಎಳೆದು ಬಿಡಿ",
    uploadClickBrowse: "ಅಥವಾ ಸಾಧನದಿಂದ ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    urbanLedger: "ನಗರ ಲೆಡ್ಜರ್",
    useCurrentGps: "ಪ್ರಸ್ತುತ GPS ಬಳಸಿ",
    verifiedRepairs: "ಪರಿಶೀಲಿಸಿದ ದುರಸ್ತಿ",
    viewContract: "ಕಾಂಟ್ರಾಕ್ಟ್ ನೋಡಿ",
    viewOnCommandCenter: "ಕಮಾಂಡ್ ಸೆಂಟರ್‌ನಲ್ಲಿ ನೋಡಿ",
    walletReady: "ವಾಲೆಟ್ ಸಿದ್ಧ",
    ward: "ವಾರ್ಡ್",
    warranty: "ವಾರಂಟಿ",
    warrantyActivated: "ವಾರಂಟಿ ಸಕ್ರಿಯ",
    warrantyGuard: "ವಾರಂಟಿ ಗಾರ್ಡ್",
    warrantyOracleListening: "ವಾರಂಟಿ ಓರಾಕಲ್ ಕೇಳುತ್ತಿದೆ",
    warrantyScanner: "ವಾರಂಟಿ ಸ್ಕ್ಯಾನರ್",
    warrantyStateVisible: "ವಾರಂಟಿ ಸ್ಥಿತಿ ನಾಗರಿಕರಿಗೆ ಗೋಚರ",
    warrantyWatch: "ವಾರಂಟಿ ನಿಗಾ",
    signUp: "ಸೈನ್ ಅಪ್",
    login: "ಲಾಗಿನ್",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    roleBasedAccess: "ಪಾತ್ರ-ಆಧಾರಿತ ಪ್ರವೇಶ",
    verifyPersonBeforeProof: "ಸಾಕ್ಷಿಗೆ ಮೊದಲು ವ್ಯಕ್ತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.",
    authPageSubtitle: "ನಾಗರಿಕರು, ಗುತ್ತಿಗೆದಾರರು ಮತ್ತು ವಾರ್ಡ್ ಅಡ್ಮಿನ್‌ಗಳಿಗೆ ವಿಭಿನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗಳಿವೆ.",
    enterEmailOtp: "ಇಮೇಲ್ OTP ನಮೂದಿಸಿ",
    createCityPraamanProfile: "CityPramaan ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    codeSentTo: "ಕೋಡ್ ಕಳಿಸಲಾಗಿದೆ",
    signingUpAs: "ಸೈನ್ ಅಪ್ ಆಗುತ್ತಿದೆ",
    loginWithEmail: "ನೋಂದಾಯಿತ ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್‌ನಿಂದ ಲಾಗಿನ್ ಮಾಡಿ.",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    contactNumber: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
    contractorIdentityArea: "ಗುತ್ತಿಗೆದಾರ ಗುರುತು ಮತ್ತು ಸೇವಾ ಪ್ರದೇಶ",
    contractorIdNo: "ಗುತ್ತಿಗೆದಾರ ID / ಗುರುತಿನ ಸಂಖ್ಯೆ",
    companyAgency: "ಕಂಪನಿ / ಏಜೆನ್ಸಿ",
    assignedAreaLocality: "ನಿಯೋಜಿತ ಪ್ರದೇಶ / ಸ್ಥಳ",
    assignedWardZone: "ನಿಯೋಜಿತ ವಾರ್ಡ್ / ಝೋನ್",
    workCategorySpecialization: "ಕೆಲಸ ವರ್ಗ / ವಿಶೇಷತೆ",
    verificationEmail: "ಪರಿಶೀಲನೆ ಇಮೇಲ್",
    otpCode: "OTP ಕೋಡ್",
    resendCode: "ಕೋಡ್ ಮತ್ತೆ ಕಳಿಸಿ",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    processing: "ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ...",
    verifyEmail: "ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    verificationEmailSent: "ಪರಿಶೀಲನೆ ಇಮೇಲ್ ಕಳಿಸಲಾಗಿದೆ.",
    verificationEmailSentAgain: "ಪರಿಶೀಲನೆ ಇಮೇಲ್ ಮತ್ತೆ ಕಳಿಸಲಾಗಿದೆ.",
    authFailed: "ದೃಢೀಕರಣ ವಿಫಲ.",
    couldNotResend: "ಪರಿಶೀಲನೆ ಕೋಡ್ ಮತ್ತೆ ಕಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
    roleUserDetail: "ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸಾಕ್ಷಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    roleAdminDetail: "ವಾರ್ಡ್ ವರದಿಗಳು, ಅನುಮೋದನೆಗಳು ಮತ್ತು ವಾರಂಟಿ ಪ್ರಕರಣಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    roleContractorDetail: "ಗುರುತು, ಪ್ರದೇಶ, ವರ್ಗ ನೋಂದಾಯಿಸಿ ಮತ್ತು ದುರಸ್ತಿ ಸಾಕ್ಷಿ ಸಲ್ಲಿಸಿ.",
    roadRepair: "ರಸ್ತೆ ದುರಸ್ತಿ",
    drainage: "ಚರಂಡಿ",
    streetlight: "ಬೀದಿ ದೀಪ",
    garbageCleanup: "ಕಸ ಸ್ವಚ್ಛತೆ",
    waterLeakage: "ನೀರು ಸೋರಿಕೆ",
    footpathRepair: "ಪಾದಚಾರಿ ದಾರಿ ದುರಸ್ತಿ",
    powerOutage: "ವಿದ್ಯುತ್ ಅಡಚಣೆ",
    generalCivicRepair: "ಸಾಮಾನ್ಯ ನಾಗರಿಕ ದುರಸ್ತಿ",
  },
};

export function translate(language: string, key: TranslationKey) {
  const languageKey = isLanguageKey(language) ? language : DEFAULT_LANGUAGE_KEY;
  return translations[languageKey][key] ?? translations.en[key];
}

export function isLanguageKey(value: string): value is LanguageKey {
  return indianLanguages.some((language) => language.key === value);
}
