
insert into public.reports (
  "id",
  "cityKey",
  "title",
  "ward",
  "status",
  "severity",
  "confidence",
  "contractor",
  "txHash",
  "warrantyDaysLeft",
  "location",
  "latitude",
  "longitude",
  "issueCategory",
  "assetType",
  "aiSummary",
  "recommendedAction",
  "slaHours",
  "aiPriorityScore",
  "imageEvidenceScore",
  "aiModelVersion",
  "estimatedImpact",
  "evidenceHash",
  "proofBundleHash",
  "history"
) values (
  'CP-SEED-001',
  'bhopal',
  'Seeded civic report from Supabase',
  'Ward 46',
  'PENDING_PROOF',
  'High',
  92,
  'Awaiting assignment',
  '0xseed...001',
  null,
  'MP Nagar Zone 1, Bhopal',
  23.2599,
  77.4126,
  'ROAD_DAMAGE',
  'City Road',
  'Seed report confirms Supabase to Command Center sync is working.',
  'Assign contractor and collect after-repair proof.',
  72,
  90,
  88,
  'CityPramaan Ruleset v0.4',
  'Demo report for backend sync verification',
  '0xseedEvidence',
  '0xseedBundle',
  '[{"label":"Seed report created","detail":"Inserted from Supabase seed file.","time":"Demo","tx":"0xseed...001"}]'::jsonb
) on conflict ("id") do nothing;
